namespace DotNetJq.DifferentialProbe;

internal sealed record BuiltinSignatureProbe(
    string Signature,
    string Filter,
    string Input);

/// <summary>
/// The public signature inventory printed by pinned jq 1.8.2's builtins/0.
/// Keeping this as checked-in test-tool data makes a missing public callable a
/// deterministic corpus-generation failure instead of an accidental coverage gap.
/// </summary>
internal static class BuiltinProbeCatalog
{
    internal static readonly string[] ExpectedSignatures =
    [
        "IN/1", "IN/2", "INDEX/1", "INDEX/2", "JOIN/2", "JOIN/3", "JOIN/4",
        "abs/0", "acos/0", "acosh/0", "add/0", "add/1", "all/0", "all/1", "all/2",
        "any/0", "any/1", "any/2", "arrays/0", "ascii_downcase/0", "ascii_upcase/0",
        "asin/0", "asinh/0", "atan/0", "atan2/2", "atanh/0", "booleans/0",
        "bsearch/1", "builtins/0", "capture/1", "capture/2", "cbrt/0", "ceil/0",
        "combinations/0", "combinations/1", "contains/1", "copysign/2", "cos/0",
        "cosh/0", "debug/0", "debug/1", "del/1", "delpaths/1", "drem/2", "empty/0",
        "endswith/1", "env/0", "erf/0", "erfc/0", "error/0", "error/1", "exp/0",
        "exp10/0", "exp2/0", "explode/0", "expm1/0", "fabs/0", "fdim/2", "finites/0",
        "first/0", "first/1", "flatten/0", "flatten/1", "floor/0", "fma/3", "fmax/2",
        "fmin/2", "fmod/2", "format/1", "frexp/0", "from_entries/0", "fromdate/0",
        "fromdateiso8601/0", "fromjson/0", "fromstream/1", "gamma/0", "get_jq_origin/0",
        "get_prog_origin/0", "get_search_list/0", "getpath/1", "gmtime/0", "group_by/1",
        "gsub/2", "gsub/3", "halt/0", "halt_error/0", "halt_error/1", "has/1",
        "have_decnum/0", "have_literal_numbers/0", "hypot/2", "implode/0", "in/1",
        "index/1", "indices/1", "infinite/0", "input/0", "input_filename/0",
        "input_line_number/0", "inputs/0", "inside/1", "isempty/1", "isfinite/0",
        "isinfinite/0", "isnan/0", "isnormal/0", "iterables/0", "j0/0", "j1/0",
        "jn/2", "join/1", "keys/0", "keys_unsorted/0", "last/0", "last/1", "ldexp/2",
        "length/0", "lgamma/0", "lgamma_r/0", "limit/2", "localtime/0", "log/0",
        "log10/0", "log1p/0", "log2/0", "logb/0", "ltrim/0", "ltrimstr/1", "map/1",
        "map_values/1", "match/1", "match/2", "max/0", "max_by/1", "min/0", "min_by/1",
        "mktime/0", "modf/0", "modulemeta/0", "nan/0", "nearbyint/0", "nextafter/2",
        "nexttoward/2", "normals/0", "not/0", "now/0", "nth/1", "nth/2", "nulls/0",
        "numbers/0", "objects/0", "path/1", "paths/0", "paths/1", "pick/1", "pow/2",
        "range/1", "range/2", "range/3", "recurse/0", "recurse/1", "recurse/2",
        "remainder/2", "repeat/1", "reverse/0", "rindex/1", "rint/0", "round/0",
        "rtrim/0", "rtrimstr/1", "scalars/0", "scalb/2", "scalbln/2", "scan/1",
        "scan/2", "select/1", "setpath/2", "significand/0", "sin/0", "sinh/0",
        "skip/2", "sort/0", "sort_by/1", "split/1", "split/2", "splits/1", "splits/2",
        "sqrt/0", "startswith/1", "stderr/0", "strflocaltime/1", "strftime/1",
        "strings/0", "strptime/1", "sub/2", "sub/3", "tan/0", "tanh/0", "test/1",
        "test/2", "tgamma/0", "to_entries/0", "toboolean/0", "todate/0",
        "todateiso8601/0", "tojson/0", "tonumber/0", "tostream/0", "tostring/0",
        "transpose/0", "trim/0", "trimstr/1", "trunc/0", "truncate_stream/1", "type/0",
        "unique/0", "unique_by/1", "until/2", "utf8bytelength/0", "values/0", "walk/1",
        "while/2", "with_entries/1", "y0/0", "y1/0", "yn/2",
    ];

    internal static IReadOnlyList<BuiltinSignatureProbe> Create()
    {
        var probes = ExpectedSignatures.Select(CreateProbe).ToArray();
        if (probes.Length != 226 ||
            probes.Select(static probe => probe.Signature).Distinct(StringComparer.Ordinal).Count() != 226)
        {
            throw new InvalidOperationException("The pinned jq public builtin inventory must contain 226 unique signatures.");
        }

        if (probes
                .Select(static probe => (probe.Filter, probe.Input))
                .Distinct()
                .Count() != 226)
        {
            throw new InvalidOperationException("Every builtin signature probe must use a unique filter/input pair.");
        }

        return probes;
    }

    private static BuiltinSignatureProbe CreateProbe(string signature)
    {
        var (filter, input) = signature switch
        {
            "IN/1" => ("IN(1,2,3)", "2"),
            "IN/2" => ("IN(1,2,3;2)", "null"),
            "INDEX/1" => ("INDEX(.id)", "[{\"id\":\"a\",\"v\":1},{\"id\":\"b\",\"v\":2}]"),
            "INDEX/2" => ("INDEX(.[];.id)", "[{\"id\":\"a\",\"v\":1},{\"id\":\"b\",\"v\":2}]"),
            "JOIN/2" => ("{\"a\":{\"id\":\"a\",\"v\":1}} as $idx | JOIN($idx;.id)", "[{\"id\":\"a\"},{\"id\":\"z\"}]"),
            "JOIN/3" => ("{\"a\":{\"id\":\"a\",\"v\":1}} as $idx | [JOIN($idx;.[];.id)]", "[{\"id\":\"a\"},{\"id\":\"z\"}]"),
            "JOIN/4" => ("{\"a\":{\"id\":\"a\",\"v\":1}} as $idx | [JOIN($idx;.[];.id;{left:.[0],right:.[1]})]", "[{\"id\":\"a\"},{\"id\":\"z\"}]"),
            "abs/0" => ("abs", "-3"),
            "acos/0" => ("acos", "0.5"),
            "acosh/0" => ("acosh", "2"),
            "add/0" => ("add", "[1,2,3]"),
            "add/1" => ("add(.[])", "[1,2,3]"),
            "all/0" => ("all", "[true,1,false]"),
            "all/1" => ("all(.>0)", "[1,2,3]"),
            "all/2" => ("all(.[];.>0)", "[1,2,3]"),
            "any/0" => ("any", "[false,0,true]"),
            "any/1" => ("any(.>2)", "[1,2,3]"),
            "any/2" => ("any(.[];.>2)", "[1,2,3]"),
            "arrays/0" => ("arrays", "[1,2]"),
            "ascii_downcase/0" => ("ascii_downcase", "\"AbCÉ\""),
            "ascii_upcase/0" => ("ascii_upcase", "\"aBcÉ\""),
            "asin/0" => ("asin", "0.5"),
            "asinh/0" => ("asinh", "2"),
            "atan/0" => ("atan", "0.5"),
            "atan2/2" => ("atan2(1;1)", "null"),
            "atanh/0" => ("atanh", "0.5"),
            "booleans/0" => ("booleans", "true"),
            "bsearch/1" => ("bsearch(2)", "[1,2,4]"),
            "builtins/0" => ("builtins|sort", "null"),
            "capture/1" => ("capture(\"(?<x>a+)\")", "\"baaac\""),
            "capture/2" => ("capture(\"(?<x>a+)\";\"\")", "\"baaac\""),
            "cbrt/0" => ("cbrt", "8"),
            "ceil/0" => ("ceil", "1.25"),
            "combinations/0" => ("[combinations]", "[[1,2],[\"a\",\"b\"]]"),
            "combinations/1" => ("[combinations(2)]", "[1,2]"),
            "contains/1" => ("contains([2])", "[1,2,3]"),
            "copysign/2" => ("copysign(2;-1)", "null"),
            "cos/0" => ("cos", "0.5"),
            "cosh/0" => ("cosh", "0.5"),
            "debug/0" => ("debug", "{\"a\":1}"),
            "debug/1" => ("debug(\"probe\")", "{\"a\":1}"),
            "del/1" => ("del(.a,.b.c)", "{\"a\":1,\"b\":{\"c\":2,\"d\":3}}"),
            "delpaths/1" => ("delpaths([[\"a\"],[\"b\",\"c\"]])", "{\"a\":1,\"b\":{\"c\":2,\"d\":3}}"),
            "drem/2" => ("drem(5;2)", "null"),
            "empty/0" => ("[empty]", "null"),
            "endswith/1" => ("endswith(\"bar\")", "\"foobar\""),
            "env/0" => ("env|type", "null"),
            "erf/0" => ("erf", "0.5"),
            "erfc/0" => ("erfc", "0.5"),
            "error/0" => ("try (\"boom\"|error) catch .", "null"),
            "error/1" => ("try error(\"boom\") catch .", "null"),
            "exp/0" => ("exp", "1"),
            "exp10/0" => ("exp10", "2"),
            "exp2/0" => ("exp2", "3"),
            "explode/0" => ("explode", "\"Aé😀\""),
            "expm1/0" => ("expm1", "0.5"),
            "fabs/0" => ("fabs", "-2.5"),
            "fdim/2" => ("fdim(5;2)", "null"),
            "finites/0" => ("finites", "1.5"),
            "first/0" => ("first", "[1,2,3]"),
            "first/1" => ("first(.[])", "[1,2,3]"),
            "flatten/0" => ("flatten", "[1,[2,[3]]]"),
            "flatten/1" => ("flatten(1)", "[1,[2,[3]]]"),
            "floor/0" => ("floor", "1.75"),
            "fma/3" => ("fma(2;3;4)", "null"),
            "fmax/2" => ("fmax(2;3)", "null"),
            "fmin/2" => ("fmin(2;3)", "null"),
            "fmod/2" => ("fmod(5;2)", "null"),
            "format/1" => ("format(\"json\")", "{\"a\":1}"),
            "frexp/0" => ("frexp", "3"),
            "from_entries/0" => ("from_entries", "[{\"key\":\"a\",\"value\":1},{\"name\":\"b\",\"Value\":2}]"),
            "fromdate/0" => ("fromdate", "\"2015-03-05T23:51:47Z\""),
            "fromdateiso8601/0" => ("fromdateiso8601", "\"2015-03-05T23:51:47Z\""),
            "fromjson/0" => ("fromjson", "\"{\\\"a\\\":[1,true]}\""),
            "fromstream/1" => ("fromstream({\"a\":[1,2]}|tostream)", "null"),
            "gamma/0" => ("gamma", "3"),
            "get_jq_origin/0" => ("([get_jq_origin]|length)<=1", "null"),
            "get_prog_origin/0" => ("([get_prog_origin]|length)<=1", "null"),
            "get_search_list/0" => ("get_search_list|type", "null"),
            "getpath/1" => ("getpath([\"a\",\"b\",1])", "{\"a\":{\"b\":[0,7]}}"),
            "gmtime/0" => ("gmtime", "0"),
            "group_by/1" => ("group_by(.k)", "[{\"k\":2,\"v\":\"a\"},{\"k\":1,\"v\":\"b\"},{\"k\":2,\"v\":\"c\"}]"),
            "gsub/2" => ("gsub(\"a\";\"X\")", "\"banana\""),
            "gsub/3" => ("gsub(\"a\";\"X\";\"i\")", "\"BanAna\""),
            "halt/0" => ("halt", "null"),
            "halt_error/0" => ("halt_error", "\"boom\""),
            "halt_error/1" => ("halt_error(7)", "\"boom\""),
            "has/1" => ("has(\"a\")", "{\"a\":null,\"b\":1}"),
            "have_decnum/0" => ("have_decnum", "null"),
            "have_literal_numbers/0" => ("have_literal_numbers", "null"),
            "hypot/2" => ("hypot(3;4)", "null"),
            "implode/0" => ("implode", "[65,233,128512]"),
            "in/1" => ("in({\"a\":1})", "\"a\""),
            "index/1" => ("index(\"an\")", "\"banana\""),
            "indices/1" => ("indices(\"an\")", "\"banana\""),
            "infinite/0" => ("infinite|isinfinite", "null"),
            "input/0" => ("try input catch .", "null"),
            "input_filename/0" => ("(input_filename==null) or (input_filename|type==\"string\")", "null"),
            "input_line_number/0" => ("(try input_line_number catch 0)|type", "null"),
            "inputs/0" => ("[inputs]", "null"),
            "inside/1" => ("inside([1,2,3])", "[2]"),
            "isempty/1" => ("isempty(.[]|select(.>9))", "[1,2,3]"),
            "isfinite/0" => ("isfinite", "1.5"),
            "isinfinite/0" => ("isinfinite", "1.5"),
            "isnan/0" => ("isnan", "0"),
            "isnormal/0" => ("isnormal", "1.5"),
            "iterables/0" => ("iterables", "{\"a\":1}"),
            "j0/0" => ("j0", "0.5"),
            "j1/0" => ("j1", "0.5"),
            "jn/2" => ("jn(2;0.5)", "null"),
            "join/1" => ("join(\"-\")", "[\"a\",2,null,true]"),
            "keys/0" => ("keys", "{\"z\":1,\"a\":2}"),
            "keys_unsorted/0" => ("keys_unsorted", "{\"z\":1,\"a\":2}"),
            "last/0" => ("last", "[1,2,3]"),
            "last/1" => ("last(.[])", "[1,2,3]"),
            "ldexp/2" => ("ldexp(0.5;3)", "null"),
            "length/0" => ("length", "\"é😀\""),
            "lgamma/0" => ("lgamma", "3"),
            "lgamma_r/0" => ("lgamma_r", "-0.5"),
            "limit/2" => ("[limit(2;.[])]", "[1,2,3]"),
            "localtime/0" => ("localtime|[length,map(type)]", "0"),
            "log/0" => ("log", "2"),
            "log10/0" => ("log10", "100"),
            "log1p/0" => ("log1p", "1e-100"),
            "log2/0" => ("log2", "8"),
            "logb/0" => ("logb", "8"),
            "ltrim/0" => ("ltrim", "\" \\t\\nabc \\r\""),
            "ltrimstr/1" => ("ltrimstr(\"foo\")", "\"foobar\""),
            "map/1" => ("map(.+1)", "[1,2,3]"),
            "map_values/1" => ("map_values(.+1)", "{\"a\":1,\"b\":2}"),
            "match/1" => ("match(\"(?<x>a+)\")", "\"baaac\""),
            "match/2" => ("match(\"(?<x>a+)\";\"g\")", "\"baaacaa\""),
            "max/0" => ("max", "[3,1,2]"),
            "max_by/1" => ("max_by(.k)", "[{\"k\":2,\"v\":\"a\"},{\"k\":1,\"v\":\"b\"},{\"k\":2,\"v\":\"c\"}]"),
            "min/0" => ("min", "[3,1,2]"),
            "min_by/1" => ("min_by(.k)", "[{\"k\":2,\"v\":\"a\"},{\"k\":1,\"v\":\"b\"},{\"k\":1,\"v\":\"c\"}]"),
            "mktime/0" => ("mktime", "[2015,2,5,23,51,47,4,63]"),
            "modf/0" => ("modf", "-2.5"),
            "modulemeta/0" => ("try (1|modulemeta) catch .", "null"),
            "nan/0" => ("nan|isnan", "null"),
            "nearbyint/0" => ("nearbyint", "2.5"),
            "nextafter/2" => ("nextafter(1;2)", "null"),
            "nexttoward/2" => ("nexttoward(1;2)", "null"),
            "normals/0" => ("normals", "1.5"),
            "not/0" => ("not", "false"),
            "now/0" => ("now|type", "null"),
            "nth/1" => ("nth(1)", "[10,20,30]"),
            "nth/2" => ("nth(1;.[])", "[10,20,30]"),
            "nulls/0" => ("nulls", "null"),
            "numbers/0" => ("numbers", "1.5"),
            "objects/0" => ("objects", "{\"a\":1}"),
            "path/1" => ("path(.a.b[1])", "{\"a\":{\"b\":[0,7]}}"),
            "paths/0" => ("[paths]", "{\"a\":[1,{\"b\":2}]}"),
            "paths/1" => ("[paths(type==\"number\")]", "{\"a\":[1,{\"b\":2}]}"),
            "pick/1" => ("pick(.a,.b.c)", "{\"a\":1,\"b\":{\"c\":2,\"d\":3}}"),
            "pow/2" => ("pow(2;3)", "null"),
            "range/1" => ("[range(3)]", "null"),
            "range/2" => ("[range(1;4)]", "null"),
            "range/3" => ("[range(1;6;2)]", "null"),
            "recurse/0" => ("[recurse]", "{\"a\":[1,2]}"),
            "recurse/1" => ("[recurse(.[]?)]", "{\"a\":[1,2]}"),
            "recurse/2" => ("[recurse(.[]?;type==\"array\" or type==\"object\")]", "{\"a\":[1,2]}"),
            "remainder/2" => ("remainder(5;2)", "null"),
            "repeat/1" => ("[limit(2;repeat(7))]", "null"),
            "reverse/0" => ("reverse", "[1,2,3]"),
            "rindex/1" => ("rindex(\"an\")", "\"banana\""),
            "rint/0" => ("rint", "2.5"),
            "round/0" => ("round", "2.5"),
            "rtrim/0" => ("rtrim", "\" \\t\\nabc \\r\""),
            "rtrimstr/1" => ("rtrimstr(\"bar\")", "\"foobar\""),
            "scalars/0" => ("scalars", "\"x\""),
            "scalb/2" => ("scalb(1.5;2)", "null"),
            "scalbln/2" => ("scalbln(1.5;2)", "null"),
            "scan/1" => ("[scan(\"a+\")]", "\"baaacaa\""),
            "scan/2" => ("[scan(\"a+\";\"i\")]", "\"bAAAcaA\""),
            "select/1" => ("select(.a>0)", "{\"a\":1}"),
            "setpath/2" => ("setpath([\"a\",\"b\",1];7)", "{\"a\":{\"b\":[0]}}"),
            "significand/0" => ("significand", "3"),
            "sin/0" => ("sin", "0.5"),
            "sinh/0" => ("sinh", "0.5"),
            "skip/2" => ("[skip(2;.[])]", "[1,2,3,4]"),
            "sort/0" => ("sort", "[3,1,2,1]"),
            "sort_by/1" => ("sort_by(.k)", "[{\"k\":2,\"v\":\"a\"},{\"k\":1,\"v\":\"b\"}]"),
            "split/1" => ("split(\"[, ]+\")", "\"a, b c\""),
            "split/2" => ("split(\"a\";\"i\")", "\"bAaA\""),
            "splits/1" => ("[splits(\"[, ]+\")]", "\"a, b c\""),
            "splits/2" => ("[splits(\"a\";\"i\")]", "\"bAaA\""),
            "sqrt/0" => ("sqrt", "2"),
            "startswith/1" => ("startswith(\"foo\")", "\"foobar\""),
            "stderr/0" => ("stderr", "{\"a\":1}"),
            "strflocaltime/1" => ("strflocaltime(\"%Y-%m-%d %H:%M:%S\")|type", "[2015,2,5,23,51,47,4,63]"),
            "strftime/1" => ("strftime(\"%Y-%m-%d %H:%M:%S\")", "[2015,2,5,23,51,47,4,63]"),
            "strings/0" => ("strings", "\"x\""),
            "strptime/1" => ("strptime(\"%Y-%m-%dT%H:%M:%SZ\")", "\"2015-03-05T23:51:47Z\""),
            "sub/2" => ("sub(\"a\";\"X\")", "\"banana\""),
            "sub/3" => ("sub(\"a\";\"X\";\"i\")", "\"Banana\""),
            "tan/0" => ("tan", "0.5"),
            "tanh/0" => ("tanh", "0.5"),
            "test/1" => ("test(\"a+\")", "\"baaac\""),
            "test/2" => ("test(\"^a\";\"i\")", "\"Abc\""),
            "tgamma/0" => ("tgamma", "3"),
            "to_entries/0" => ("to_entries", "{\"z\":1,\"a\":2}"),
            "toboolean/0" => ("toboolean", "\"true\""),
            "todate/0" => ("todate", "0"),
            "todateiso8601/0" => ("todateiso8601", "0"),
            "tojson/0" => ("tojson", "{\"a\":[1,true]}"),
            "tonumber/0" => ("tonumber", "\"12.5\""),
            "tostream/0" => ("[tostream]", "{\"a\":[1,2]}"),
            "tostring/0" => ("tostring", "{\"a\":1}"),
            "transpose/0" => ("transpose", "[[1,2],[3]]"),
            "trim/0" => ("trim", "\" \\t\\nabc \\r\""),
            "trimstr/1" => ("trimstr(\"xy\")", "\"xyhelloxy\""),
            "trunc/0" => ("trunc", "-2.75"),
            "truncate_stream/1" => ("[1|truncate_stream({\"a\":{\"b\":1}}|tostream)]", "null"),
            "type/0" => ("type", "{\"a\":1}"),
            "unique/0" => ("unique", "[3,1,2,1]"),
            "unique_by/1" => ("unique_by(.k)", "[{\"k\":2,\"v\":\"a\"},{\"k\":1,\"v\":\"b\"},{\"k\":2,\"v\":\"c\"}]"),
            "until/2" => ("until(.>=3;.+1)", "0"),
            "utf8bytelength/0" => ("utf8bytelength", "\"é😀\""),
            "values/0" => ("values", "0"),
            "walk/1" => ("walk(if type==\"number\" then .+1 else . end)", "{\"a\":[1,2]}"),
            "while/2" => ("[while(.<3;.+1)]", "0"),
            "with_entries/1" => ("with_entries(.key|=ascii_upcase)", "{\"a\":1,\"b\":2}"),
            "y0/0" => ("y0", "2"),
            "y1/0" => ("y1", "1"),
            "yn/2" => ("yn(2;4)", "null"),
            _ => throw new InvalidOperationException($"No representative probe is defined for {signature}."),
        };

        return new BuiltinSignatureProbe(signature, filter, input);
    }
}
