#!/usr/bin/env perl
use strict;
use warnings;
use Digest::SHA qw(sha256_hex);

my $check = @ARGV && $ARGV[0] eq '--check' ? shift(@ARGV) : 0;
die "usage: $0 [--check] unicode_fold_data.c OnigurumaSimpleCaseFoldData.cs\n"
    unless @ARGV == 2;
my ($source_path, $output_path) = @ARGV;

open my $source_file, '<:raw', $source_path or die "cannot read $source_path: $!\n";
local $/;
my $source = <$source_file>;
close $source_file;

my ($version) = $source =~ /#define\s+UNICODE_CASEFOLD_VERSION\s+(\d+)/;
die "missing UNICODE_CASEFOLD_VERSION\n" unless defined $version;
my ($folds1) = $source =~ /OnigCodePoint\s+OnigUnicodeFolds1\[\]\s*=\s*\{(.*?)\n\};/s;
die "missing OnigUnicodeFolds1\n" unless defined $folds1;

my @pairs;
my $groups = 0;
for my $line (split /\n/, $folds1) {
    next unless $line =~ m{^\s*/\*\s*\d+\*/};
    $line =~ s{^\s*/\*.*?\*/\s*}{};
    $line =~ s{/\*.*$}{};
    my @values = map { /^0x/ ? hex($_) : int($_) } ($line =~ /(0x[0-9a-fA-F]+|\d+)/g);
    die "malformed folds1 row: $line\n" unless @values >= 3;
    my ($canonical, $count, @equivalents) = @values;
    die "fold count mismatch: $line\n" unless @equivalents == $count;
    push @pairs, map { [$_, $canonical] } @equivalents;
    $groups++;
}

my $sha = sha256_hex($source);
my @lines;
for (my $index = 0; $index < @pairs; $index += 4) {
    my $last = $index + 3 < $#pairs ? $index + 3 : $#pairs;
    push @lines, '        ' . join(', ', map {
        sprintf('0x%06X, 0x%06X', $pairs[$_][0], $pairs[$_][1])
    } $index .. $last) . ',';
}
my $pair_lines = join("\n", @lines);
my $pair_count = scalar @pairs;

my $generated = <<"CS";
// <auto-generated />
// DOTNETJQ GENERATED COMPATIBILITY DATA
// Upstream revision: 34f7186b86743a083a589741b6cea95293524108 (jq-1.8.2)
// Source: vendor/oniguruma/src/unicode_fold_data.c
// UNICODE_CASEFOLD_VERSION: $version
// Source SHA-256: $sha
// Simple-fold groups: $groups; non-canonical members: $pair_count.

namespace DotNetJq.Compatibility.Regex;

internal static class OnigurumaSimpleCaseFoldData
{
    private static readonly int[] MemberCanonicalPairs =
    [
$pair_lines
    ];

    private static readonly Lazy<IReadOnlyDictionary<int, int>> CanonicalByMember =
        new(BuildCanonicalByMember);

    internal static ReadOnlySpan<int> MemberCanonicalMap => MemberCanonicalPairs;

    internal static int Canonicalize(int scalar) =>
        CanonicalByMember.Value.TryGetValue(scalar, out var canonical) ? canonical : scalar;

    private static IReadOnlyDictionary<int, int> BuildCanonicalByMember()
    {
        var result = new Dictionary<int, int>(MemberCanonicalPairs.Length / 2);
        for (var index = 0; index < MemberCanonicalPairs.Length; index += 2)
        {
            result.Add(MemberCanonicalPairs[index], MemberCanonicalPairs[index + 1]);
        }

        return result;
    }
}
CS

if ($check) {
    open my $actual_file, '<:raw', $output_path or die "cannot read $output_path: $!\n";
    my $actual = <$actual_file>;
    close $actual_file;
    die "$output_path is stale\n" unless $actual eq $generated;
    print "unicode_casefold_version=$version sha256=$sha groups=$groups pairs=$pair_count exact\n";
    exit 0;
}

open my $output_file, '>:raw', $output_path or die "cannot write $output_path: $!\n";
print {$output_file} $generated;
close $output_file;
print "wrote $output_path: version=$version groups=$groups pairs=$pair_count\n";
