#!/usr/bin/env perl

use strict;
use warnings;

my $mode = '--corpus';
my $check_path;
if (@ARGV && $ARGV[0] eq '--alias-map') {
    $mode = shift(@ARGV);
}
elsif (@ARGV && $ARGV[0] eq '--check') {
    $mode = shift(@ARGV);
    $check_path = shift(@ARGV);
}
my ($unicode_path, $posix_path) = @ARGV;
die "usage: $0 [--alias-map | --check generated.cs] unicode_property_data.c unicode_property_data_posix.c\n"
    if !defined($unicode_path) || !defined($posix_path) || @ARGV != 2 ||
       ($mode eq '--check' && !defined($check_path));

my $unicode = slurp($unicode_path);
my $posix = slurp($posix_path);

my ($main_tables, $main_order) = parse_tables($unicode);
my ($posix_tables, $posix_order) = parse_tables($posix);
my $macros = parse_macros($unicode);
my @code_ranges = parse_code_ranges($unicode);
my @aliases = parse_aliases($unicode, \@code_ranges);

my %main_by_normalized;
for my $name (@$main_order) {
    $main_by_normalized{normalize($name)} //= [$name, $main_tables->{$name}];
}

die "expected 612 normalized main tables, got " . scalar(keys(%main_by_normalized)) . "\n"
    if keys(%main_by_normalized) != 612;
die "expected 15 POSIX tables, got " . scalar(@$posix_order) . "\n"
    if @$posix_order != 15;
die "expected 629 CodeRanges entries, got " . scalar(@code_ranges) . "\n"
    if @code_ranges != 629;
die "expected 886 aliases, got " . scalar(@aliases) . "\n"
    if @aliases != 886;

if ($mode eq '--alias-map') {
    for my $alias (@aliases) {
        my ($name, $target) = @$alias;
        my $resolved = resolve_macro($target, $macros);
        print '            ["' . normalize($name) . '"] = "' .
            normalize($resolved) . "\",\n";
    }
    exit(0);
}

my $generated = <<'CSHARP';
// DOTNETJQ DIFFERENTIAL TEST DATA
// Upstream revision: 34f7186b86743a083a589741b6cea95293524108 (jq-1.8.2)
// Generated by generate-regex-unicode-property-corpus.pl directly from the pinned
// Oniguruma Unicode 16.0 property tables and gperf lookup table. Each probe uses
// a valid Unicode scalar member and nonmember where the table has one.

namespace DotNetJq.DifferentialProbe;

internal static class RegexUnicodePropertyCorpus
{
    internal const int MainTableCount = 612;
    internal const int PosixTableCount = 15;
    internal const int AliasCount = 886;
    internal const int ProbeCount = MainTableCount + PosixTableCount + AliasCount;

    internal static readonly string[] Filters =
    [
CSHARP

for my $normalized (sort keys(%main_by_normalized)) {
    my ($name, $ranges) = @{$main_by_normalized{$normalized}};
    $generated .= build_probe('main', $name, $ranges);
}

for my $name (@$posix_order) {
    $generated .= build_probe('posix', $name, $posix_tables->{$name});
}

for my $alias (@aliases) {
    my ($name, $target) = @$alias;
    my $resolved = resolve_macro($target, $macros);
    die "alias '$name' resolves to missing table '$resolved'\n"
        if !exists($main_tables->{$resolved});
    $generated .= build_probe('alias', $name, $main_tables->{$resolved});
}

$generated .= <<'CSHARP';
    ];

    static RegexUnicodePropertyCorpus()
    {
        if (Filters.Length != ProbeCount)
        {
            throw new InvalidOperationException(
                $"Generated Unicode regex property corpus contains {Filters.Length} probes; expected {ProbeCount}.");
        }
    }
}
CSHARP

if ($mode eq '--check') {
    my $actual = slurp_raw($check_path);
    die "generated regex Unicode property corpus is stale: $check_path\n"
        if $actual ne $generated;
    print "generated regex Unicode property corpus is current: $check_path\n";
}
else {
    print $generated;
}

sub slurp {
    my ($path) = @_;
    open(my $handle, '<', $path) or die "cannot read $path: $!\n";
    local $/;
    return <$handle>;
}

sub slurp_raw {
    my ($path) = @_;
    open(my $handle, '<:raw', $path) or die "cannot read $path: $!\n";
    local $/;
    return <$handle>;
}

sub parse_tables {
    my ($source) = @_;
    my %tables;
    my @order;
    while ($source =~ /^CR_([A-Za-z0-9_]+)\[\]\s*=\s*\{\s*(\d+)\s*,(.*?)^\};\s*\/\* END of CR_\1 \*\//msg) {
        my ($name, $declared_count, $body) = ($1, $2, $3);
        my @points = map { hex($_) } ($body =~ /0x([0-9a-fA-F]+)/g);
        die "table '$name' declares $declared_count ranges but has " . (@points / 2) . "\n"
            if @points != $declared_count * 2;
        die "duplicate table '$name'\n" if exists($tables{$name});
        $tables{$name} = \@points;
        push(@order, $name);
    }
    return (\%tables, \@order);
}

sub parse_macros {
    my ($source) = @_;
    my %macros = $source =~ /^#define CR_([A-Za-z0-9_]+) CR_([A-Za-z0-9_]+)\s*$/mg;
    return \%macros;
}

sub parse_code_ranges {
    my ($source) = @_;
    $source =~ /const CodeRanges\[\]\s*=\s*\{(.*?)^\};/ms
        or die "CodeRanges table not found\n";
    return ($1 =~ /\bCR_([A-Za-z0-9_]+)/g);
}

sub parse_aliases {
    my ($source, $code_ranges) = @_;
    my %pool = $source =~ /unicode_prop_name_pool_str(\d+)\[sizeof\("([^"]+)"\)\]/g;
    $source =~ /wordlist\[\]\s*=\s*\{(.*?)^\s*\};/ms
        or die "gperf wordlist not found\n";
    my $wordlist = $1;
    my @aliases;
    while ($wordlist =~ /\{pool_offset\((\d+)\),\s*(\d+)\}/g) {
        my ($pool_id, $range_index) = ($1, $2);
        die "missing string-pool entry $pool_id\n" if !exists($pool{$pool_id});
        die "CodeRanges index $range_index is out of bounds\n"
            if $range_index >= @$code_ranges;
        push(@aliases, [$pool{$pool_id}, $code_ranges->[$range_index]]);
    }
    @aliases = sort { lc($a->[0]) cmp lc($b->[0]) } @aliases;
    return @aliases;
}

sub resolve_macro {
    my ($name, $macros) = @_;
    my %seen;
    while (exists($macros->{$name})) {
        die "macro cycle at '$name'\n" if $seen{$name}++;
        $name = $macros->{$name};
    }
    return $name;
}

sub normalize {
    my ($name) = @_;
    $name = uc($name);
    $name =~ s/[^A-Z0-9]//g;
    return $name;
}

sub build_probe {
    my ($kind, $property, $ranges) = @_;
    my $member = first_member($ranges);
    my $nonmember = first_nonmember($ranges);
    my $member_check = defined($member)
        ? '(' . jq_scalar($member) . '|test("\\\\p{' . $property . '}"))'
        : 'null';
    my $nonmember_check = defined($nonmember)
        ? '(' . jq_scalar($nonmember) . '|(test("\\\\p{' . $property . '}")|not))'
        : 'null';
    my $filter = '["' . $kind . '","' . $property . '",' .
        $member_check . ',' . $nonmember_check . ']';
    return '        "' . csharp_escape($filter) . '",' . "\n";
}

sub first_member {
    my ($ranges) = @_;
    for (my $index = 0; $index < @$ranges; $index += 2) {
        my ($start, $end) = ($ranges->[$index], $ranges->[$index + 1]);
        next if $start > 0x10ffff;
        $end = 0x10ffff if $end > 0x10ffff;
        return $start if $start < 0xd800;
        return 0xe000 if $start <= 0xe000 && $end >= 0xe000;
        return $start if $start > 0xdfff;
    }
    return undef;
}

sub first_nonmember {
    my ($ranges) = @_;
    my @candidates = (0x0000, 0x0041, 0x0020, 0x007f, 0x00a0, 0x0378,
        0x2000, 0x4e00, 0xfffd, 0x10000, 0x1f600, 0x10ffff);
    for my $candidate (@candidates) {
        return $candidate if !contains($ranges, $candidate);
    }

    my $candidate = 0;
    for (my $index = 0; $index < @$ranges && $candidate <= 0x10ffff; $index += 2) {
        my ($start, $end) = ($ranges->[$index], $ranges->[$index + 1]);
        return $candidate if $candidate < $start;
        $candidate = $end + 1 if $candidate <= $end;
        $candidate = 0xe000 if $candidate >= 0xd800 && $candidate <= 0xdfff;
    }
    return $candidate <= 0x10ffff ? $candidate : undef;
}

sub contains {
    my ($ranges, $candidate) = @_;
    for (my $index = 0; $index < @$ranges; $index += 2) {
        return 0 if $candidate < $ranges->[$index];
        return 1 if $candidate <= $ranges->[$index + 1];
    }
    return 0;
}

sub jq_scalar {
    my ($codepoint) = @_;
    return sprintf('"\\u%04X"', $codepoint) if $codepoint <= 0xffff;
    my $value = $codepoint - 0x10000;
    my $high = 0xd800 + ($value >> 10);
    my $low = 0xdc00 + ($value & 0x3ff);
    return sprintf('"\\u%04X\\u%04X"', $high, $low);
}

sub csharp_escape {
    my ($value) = @_;
    $value =~ s/\\/\\\\/g;
    $value =~ s/"/\\"/g;
    return $value;
}
