namespace DotNetJq.DifferentialProbe;

internal static class RegexCorpus
{
    internal const int DefaultSeed = 1_808_202;
    internal static int DefaultCount => Groups
        .SelectMany(group => group.Filters.SelectMany(filter =>
            group.Inputs.Select(input => (Filter: filter, Input: input))))
        .Distinct()
        .Count();

    private static readonly Group[] Groups =
    [
        new(
            "regex-captures",
            [
                "match(\"(a)(b)?\"; \"g\")?",
                "match(\"(?<x>a)(?<y>b)?\"; \"g\")?",
                "capture(\"(?<x>a+)(?<y>b*)\")?",
                "[scan(\"(a+)(b*)\")]?",
                "match(\"(?P<x>a)(?'y'b)?\"; \"g\")?",
                "match(\"((a)|(b))\"; \"g\")?",
                "capture(\"(?<x>a)|(?<y>b)\")?",
                "match(\"(?<x>a)(?<x>b)\"; \"g\")?",
            ],
            ["\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"aba\"", "\"aabbb\"", "\"A,b z\"", "\"é😀\""]),
        new(
            "regex-posix",
            [
                "[scan(\"[[:alpha:]]+\")]?",
                "[scan(\"[[:alnum:]]+\")]?",
                "[scan(\"[[:digit:]]+\")]?",
                "[scan(\"[[:space:]]+\")]?",
                "[scan(\"[[:word:]]+\")]?",
                "[scan(\"[[:upper:]]+\")]?",
                "[scan(\"[[:lower:]]+\")]?",
                "[scan(\"[^[:alpha:]]+\")]?",
            ],
            ["\"\"", "\"A,b z\"", "\"abcXYZ09_\"", "\"é α\"", "\"١２9\"", "\" \\t\\n\"", "\"-_$\"", "\"😀Ａｚ\""]),
        new(
            "regex-unicode",
            [
                "[scan(\"\\\\p{L}+\")]?",
                "[scan(\"\\\\p{N}+\")]?",
                "[scan(\"\\\\P{L}+\")]?",
                "[scan(\"\\\\w+\")]?",
                "[scan(\"\\\\d+\")]?",
                "test(\"é\"; \"i\")?",
                "test(\"k\"; \"i\")?",
                "test(\"σ\"; \"i\")?",
            ],
            ["\"\"", "\"éÉe\"", "\"kKK\"", "\"σΣς\"", "\"١２9\"", "\"A_́\"", "\"😀𐐀𝟘\"", "\"straße STRASSE\""]),
        new(
            "regex-full-fold-atom-boundaries",
            [
                "\"ß\" | test(\"ss\";\"i\")",
                "\"ß\" | test(\"ss+\";\"i\")",
                "\"ﬃ\" | test(\"ss*\";\"i\")",
                "\"ß\" | test(\"ss?\";\"i\")",
                "\"ß\" | test(\"ss{1,2}\";\"i\")",
                "\"ß\" | test(\"ss+?\";\"i\")",
                "\"ß\" | test(\"ss++\";\"i\")",
                "\"sss\" | test(\"ss{2}\";\"i\")",
                "\"ß\" | test(\"s{1}s\";\"i\")",
                "\"ß\" | test(\"ss{1}\";\"i\")",
                "\"ß\" | test(\"s{1,1}s\";\"i\")",
                "\"ß\" | test(\"ss{1,1}\";\"i\")",
                "\"ß\" | test(\"s{1}?s\";\"i\")",
                "\"ß\" | test(\"s{1}+s\";\"i\")",
                "\"ß\" | test(\"(?:ss){1,2}\";\"i\")",
                "\"ß\" | test(\"(?:ss)+?\";\"i\")",
                "\"ß\" | test(\"(?:ss)++\";\"i\")",
                "\"ß\" | test(\"(?:s)s\";\"i\")",
                "\"ß\" | test(\"s(?:s)\";\"i\")",
                "\"ß\" | test(\"s(?:)s\";\"i\")",
                "\"ß\" | test(\"(s)s\";\"i\")",
                "\"ß\" | test(\"s(s)\";\"i\")",
                "\"ß\" | test(\"s(?>)s\";\"i\")",
                "\"ß\" | test(\"s(?=)s\";\"i\")",
                "\"ß\" | test(\"[s]s\";\"i\")",
                "\"ß\" | test(\"s[s]\";\"i\")",
                "\"ß\" | test(\"(?i:s)s\";\"\")",
                "\"ß\" | test(\"s(?i:s)\";\"\")",
                "\"ß\" | test(\"(?i:s)(?i:s)\";\"\")",
                "\"ß\" | test(\"(?:ss|x)+\";\"i\")",
                "\"ß\" | test(\"s(?:s|x)\";\"i\")",
                "\"ß\" | test(\"(?:ss|s)+\";\"i\")",
                "\"ß\" | test(\"s s\";\"ix\")",
                "\"ß\" | test(\"s# comment\\ns\";\"ix\")",
                "\"ß\" | test(\"(?x:s s)\";\"i\")",
                "\"ß\" | test(\"(?x)s(?-x) s\";\"i\")",
                "\"ß\" | test(\"s\\\\Qs\\\\E\";\"i\")",
                "\"ß\" | test(\"\\\\Qs\\\\Es\";\"i\")",
                "\"ß\" | test(\"\\\\Qss\\\\E\";\"i\")",
                "\"ß\" | test(\"s\\\\Q\\\\Es\";\"i\")",
                "\"ß\" | test(\"\\\\x73s\";\"i\")",
                "\"ß\" | test(\"s\\\\x73\";\"i\")",
                "\"ß\" | test(\"\\\\x{73 73}\";\"i\")",
                "\"ﬃ\" | test(\"ffi+\";\"i\")",
                "\"ß\" | test(\"ffi?\";\"i\")",
                "\"ﬃ\" | test(\"f\\\\Qfi\\\\E\";\"i\")",
                "\"ﬃ\" | test(\"\\\\Qf\\\\Ef\\\\Qi\\\\E\";\"i\")",
                "\"ﬃ\" | test(\"\\\\x66\\\\x66\\\\x69\";\"i\")",
                "\"ﬀi\" | test(\"ffi\";\"i\")",
                "\"fﬁ\" | test(\"ffi\";\"i\")",
                "\"SSx\" | test(\"(?<=ß)x\";\"i\")",
                "\"ẞx\" | test(\"(?<=ß)x\";\"i\")",
                "\"ﬃx\" | test(\"(?<=ffi)x\";\"i\")",
                "\"@\" | test(\"[\\\\w-a]\";\"i\")",
                "\"-\" | test(\"[\\\\w-a]\";\"i\")",
                "\"@\" | test(\"[[:digit:]-a]\";\"i\")",
                "\"-\" | test(\"[[:digit:]-a]\";\"i\")",
            ],
            ["null"]),
        new(
            "regex-zero-width",
            [
                "[match(\"\"; \"g\") | .offset]?",
                "[match(\"a*\"; \"g\") | [.offset,.length]]?",
                "[scan(\"(?:a|b)*\")]?",
                "[match(\"(?=a)\"; \"g\") | .offset]?",
                "[match(\"(?!a)\"; \"g\") | .offset]?",
                "gsub(\"\"; \"-\")?",
                "[splits(\"\")]?",
                "split(\"\"; \"\")?",
            ],
            ["\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"é\"", "\"😀\"", "\"é😀\"", "\"aé😀b\""]),
        new(
            "regex-lookarounds",
            [
                "[scan(\"a(?=b)\")]?",
                "[scan(\"a(?!b)\")]?",
                "[scan(\"(?<=a)b\")]?",
                "[scan(\"(?<!a)b\")]?",
                "match(\"(?=(?<x>a))\"; \"g\")?",
                "match(\"(?<=(a))b\"; \"g\")?",
                "[scan(\"(?=.)\")]?",
                "[scan(\"(?!. )\"; \"x\")]?",
            ],
            ["\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"ba\"", "\"aab\"", "\"é😀\"", "\"a\\nb\""]),
        new(
            "regex-backreferences",
            [
                "[scan(\"(a)\\\\1\")]?",
                "[scan(\"(a)(b)\\\\2\\\\1\")]?",
                "[scan(\"(?<x>a)\\\\k<x>\")]?",
                "[scan(\"(?P<x>a)(?P=x)\")]?",
                "[scan(\"(?<x>a)(?<x>b)\\\\k<x>\")]?",
                "[scan(\"(a)?b\\\\1\")]?",
                "[scan(\"(.)\\\\1\")]?",
                "[scan(\"(é)\\\\1\")]?",
            ],
            ["\"\"", "\"a\"", "\"aa\"", "\"aba\"", "\"abb\"", "\"baa\"", "\"éé😀😀\"", "\"abcabc\""]),
        new(
            "regex-options",
            [
                "[scan(\"a.b\"; \"m\")]?",
                "[scan(\"^b\"; \"s\")]?",
                "[scan(\"^b\"; \"p\")]?",
                "[scan(\"a b #comment\"; \"x\")]?",
                "[scan(\"(?i:a)b\")]?",
                "[scan(\"(?s:a.b)\")]?",
                "[scan(\"(?x:a b)\")]?",
                "match(\"a|aa\"; \"gl\")?",
            ],
            ["\"\"", "\"ab\"", "\"a b\"", "\"a\\nb\"", "\"AbaB\"", "\"b\\nb\"", "\"aa\"", "\"é\\n😀\""]),
        new(
            "regex-empty-alternatives",
            [
                "[scan(\"a|\")]?",
                "[scan(\"|a\")]?",
                "[scan(\"(?:a|b)*\")]?",
                "[scan(\"(?:|a)+\")]?",
                "match(\"a*?\"; \"g\")?",
                "match(\"(?:a?|b?)\"; \"g\")?",
                "gsub(\"a|\"; \"X\")?",
                "[splits(\"a|\")]?",
            ],
            ["\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"ba\"", "\"aa\"", "\"é\"", "\"é😀\""]),
        new(
            "regex-anchors",
            [
                "[match(\"^\"; \"g\") | .offset]?",
                "[match(\"$\"; \"g\") | .offset]?",
                "[match(\"^|$\"; \"g\") | .offset]?",
                "[scan(\"^a\")]?",
                "[scan(\"a$\")]?",
                "[scan(\"\\\\Aa\")]?",
                "[scan(\"a\\\\z\")]?",
                "[match(\"^.$\"; \"g\") | [.offset,.length]]?",
            ],
            ["\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"a\\n\"", "\"a\\nb\"", "\"é\"", "\"😀\""]),
        new(
            "regex-invalid",
            [
                "test(\"(\")",
                "test(\"[\")",
                "test(\"*a\")",
                "test(\"a{2,1}\")",
                "test(\"(?z:a)\")",
                "test(\"(?<>a)\")",
                "test(\"\\\\k<missing>\")",
                "test(\"[z-a]\")",
            ],
            ["\"\"", "\"a\"", "\"ab\"", "\"(\"", "\"[\"", "\"é\"", "\"😀\"", "\"a\\nb\""]),
        new(
            "regex-replace-split",
            [
                "sub(\"a\"; \"X\")?",
                "gsub(\"a*\"; \"X\")?",
                "gsub(\"(?<x>a)\"; \"<\\(.x)>\")?",
                "gsub(\"(?<x>a)?b\"; \"<\\(.x // \\\"-\\\")>\")?",
                "split(\"[, ]+\"; \"\")?",
                "split(\"a\"; \"i\")?",
                "[splits(\"[, ]+\")]?",
                "[splits(\"(?=a)\")]?",
            ],
            ["\"\"", "\"a\"", "\"A\"", "\"ab\"", "\"aba\"", "\"A,b z\"", "\"é😀\"", "\"a,a  b\""]),
        new(
            "regex-perl-ng-syntax",
            [
                "[scan(\"\\\\Q.a+[]()\\\\E\")]?",
                "[scan(\"\\\\x{1F600}\")]?",
                "[scan(\"\\\\o{141}\")]?",
                "[scan(\"\\\\cA\")]?",
                "[scan(\"\\\\e\")]?",
                "[scan(\"a++a\")]?",
                "[scan(\"a*+a\")]?",
                "[scan(\"a{1,2}+a\")]?",
                "[scan(\"(?>a|ab)c\")]?",
                "[scan(\"(a)?(?(1)b|c)\")]?",
                "[scan(\"a{,2}\")]?",
                "[scan(\"(?i)te(?-i)st\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"aa\"", "\"aaa\"", "\"aac\"", "\"ab\"",
                "\"ac\"", "\"c\"", "\".a+[]()\"", "\"😀\"", "\"TEst\"", "\"\\u0001\\u001b\"",
            ]),
        new(
            "regex-properties",
            [
                "[scan(\"\\\\p{Alpha}+\")]?",
                "[scan(\"\\\\p{Alnum}+\")]?",
                "[scan(\"\\\\p{Word}+\")]?",
                "[scan(\"\\\\p{Digit}+\")]?",
                "[scan(\"\\\\p{Space}+\")]?",
                "[scan(\"\\\\p{Greek}+\")]?",
                "[scan(\"\\\\p{Latin}+\")]?",
                "[scan(\"\\\\p{M}+\")]?",
                "[scan(\"\\\\p{Z}+\")]?",
                "[scan(\"\\\\p{P}+\")]?",
                "[scan(\"\\\\p{S}+\")]?",
                "[scan(\"\\\\p{^L}+\")]?",
            ],
            [
                "\"\"", "\"abcXYZ09_\"", "\"éÉ αΩ\"", "\"١２9\"", "\"A_́\"", "\"😀𐐀𝟘\"",
                "\" \\t\\n\\u00a0\"", "\".,!?$+\"", "\"Жжβ\"", "\"中文かな\"", "\"Ⅻ½\"", "\"\\u0000\\u0085\"",
            ]),
        new(
            "regex-posix-composition",
            [
                "[scan(\"[[:ascii:]]+\")]?",
                "[scan(\"[[:blank:]]+\")]?",
                "[scan(\"[[:cntrl:]]+\")]?",
                "[scan(\"[[:graph:]]+\")]?",
                "[scan(\"[[:print:]]+\")]?",
                "[scan(\"[[:punct:]]+\")]?",
                "[scan(\"[[:xdigit:]]+\")]?",
                "[scan(\"[[:^digit:]]+\")]?",
                "[scan(\"[A-F[:digit:]]+\")]?",
                "[scan(\"[^A-F[:digit:]]+\")]?",
                "[scan(\"[[:alpha:]_.-]+\")]?",
                "[scan(\"[[:word:][:space:]]+\")]?",
            ],
            [
                "\"\"", "\"ABCdef019\"", "\"A-F_9\"", "\"é α\"", "\"١２9\"", "\" \\t\\n\\u00a0\"",
                "\".,!?$+\"", "\"\\u0000\\u001f\\u007f\\u0085\"", "\"😀Ａｚ\"", "\"deadBEEF xyz\"", "\"a_b-c.d\"", "\"Z9! \\n\"",
            ]),
        new(
            "regex-casefold",
            [
                "[scan(\"k\"; \"i\")]?",
                "[scan(\"s\"; \"i\")]?",
                "[scan(\"σ\"; \"i\")]?",
                "[scan(\"i\"; \"i\")]?",
                "[scan(\"ß\"; \"i\")]?",
                "[scan(\"ff\"; \"i\")]?",
                "[scan(\"å\"; \"i\")]?",
                "[scan(\"𐐀\"; \"i\")]?",
                "[scan(\"[a-z]+\"; \"i\")]?",
                "[scan(\"\\\\x{6b}\"; \"i\")]?",
                "[scan(\"(?i:k)\")]?",
                "[scan(\"(?i)k(?-i)s\")]?",
                "[scan(\"İ\"; \"i\")]?",
                "[scan(\"ŉ\"; \"i\")]?",
                "[scan(\"ﬓ\"; \"i\")]?",
                "[scan(\"ΐ\"; \"i\")]?",
                "[scan(\"[ß]\"; \"i\")]?",
                "[scan(\"[ﬃ]\"; \"i\")]?",
            ],
            [
                "\"\"", "\"kKK\"", "\"sSſ\"", "\"σΣς\"", "\"iIİı\"", "\"ßSSẞ\"",
                "\"ffﬀﬁ\"", "\"åÅÅ\"", "\"𐐀𐐨\"", "\"straße STRASSE\"", "\"Kelvin K\"", "\"kiKs\"",
                "\"İíi̇\"", "\"ŉʼnʼN\"", "\"ﬓմնՄՆ\"", "\"ΐΐΪ́\"", "\"ﬃffiFFI\"", "\"ﬃﬀifﬁ\"",
            ]),
        new(
            "regex-word-boundaries",
            [
                "[match(\"\\\\b\"; \"g\") | .offset]?",
                "[match(\"\\\\B\"; \"g\") | .offset]?",
                "[scan(\"\\\\b\\\\w+\\\\b\")]?",
                "[scan(\"\\\\W+\")]?",
                "[scan(\"\\\\S+\")]?",
                "[scan(\"\\\\D+\")]?",
                "[match(\"^|$\"; \"g\") | .offset]?",
                "[match(\"\\\\A|\\\\z\"; \"g\") | .offset]?",
                "[scan(\"^.$\")]?",
                "[scan(\"^.$\"; \"s\")]?",
                "[scan(\"^.$\"; \"m\")]?",
                "[scan(\"^.$\"; \"p\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"_\"", "\"é\"", "\"𐐀\"", "\"𝟘\"",
                "\"a b\"", "\"á\"", "\"😀\"", "\"a\\n\"", "\"a\\nb\"", "\"\\r\\n\"",
            ]),
        new(
            "regex-empty-modifiers",
            [
                "match(\"a|\"; \"g\")?",
                "match(\"a|\"; \"gn\")?",
                "match(\"|a\"; \"g\")?",
                "match(\"|a\"; \"gn\")?",
                "match(\"a*?\"; \"g\")?",
                "match(\"a*?\"; \"gn\")?",
                "match(\"a*?\"; \"gl\")?",
                "match(\"a*?\"; \"gln\")?",
                "[scan(\"(?:|a)+\"; \"n\")]?",
                "gsub(\"|a\"; \"X\")?",
                "[splits(\"|a\"; \"n\")]?",
                "split(\"a|\"; \"n\")?",
            ],
            [
                "\"\"", "\"a\"", "\"aa\"", "\"b\"", "\"ab\"", "\"ba\"",
                "\"aba\"", "\"bbb\"", "\"é\"", "\"😀\"", "\"aé\"", "\"éa😀\"",
            ]),
        new(
            "regex-capture-adversarial",
            [
                "match(\"()\"; \"g\")?",
                "match(\"(a*)\"; \"g\")?",
                "match(\"((a)?)(b*)\"; \"g\")?",
                "match(\"(?<x>a*)(?<y>b*)\"; \"g\")?",
                "match(\"(?<x>a)|(?<x>b)|(?<x>c)\"; \"g\")?",
                "capture(\"(?<x>a)?(?<y>b)?\")?",
                "[scan(\"(a)?(b)?\")]?",
                "[scan(\"(?<x>a)?(?<y>b)?\")]?",
                "match(\"((?=(a)))\"; \"g\")?",
                "match(\"(?<x>a)(?<x>b)\\\\k<x>\"; \"g\")?",
                "match(\"(a)(b)\\\\2\\\\1\"; \"g\")?",
                "match(\"(?<x>a)|(?<y>b)\"; \"gl\")?",
            ],
            [
                "\"\"", "\"a\"", "\"b\"", "\"c\"", "\"ab\"", "\"abb\"",
                "\"aba\"", "\"ba\"", "\"abc\"", "\"aaabbb\"", "\"é😀\"", "\"aéa\"",
            ]),
        new(
            "regex-zero-width-context",
            [
                "[match(\"(?=.)\"; \"g\") | .offset]?",
                "[match(\"(?<=a)\"; \"g\") | .offset]?",
                "[match(\"(?=a)|$\"; \"g\") | .offset]?",
                "[match(\"^|(?=a)\"; \"g\") | .offset]?",
                "[match(\"(?<!a)\"; \"g\") | .offset]?",
                "[match(\"(?!a)\"; \"g\") | .offset]?",
                "[match(\"a*\"; \"g\") | [.offset,.length,.string]]?",
                "[match(\".*?\"; \"g\") | [.offset,.length,.string]]?",
                "gsub(\"(?=.)\"; \"-\")?",
                "[splits(\"(?=.)\")]?",
                "split(\"(?<=a)\"; \"\")?",
                "[scan(\"(?=(.))\")]?",
                "[match(\"(?<=.)\"; \"g\") | .offset]?",
                "[match(\"(?<=\\\\O)\"; \"g\") | .offset]?",
                "[match(\"(?<=\\\\w)\"; \"g\") | .offset]?",
                "[match(\"(?<=.)|Z\"; \"g\") | .offset]?",
                "[match(\"Z|(?<=.)\"; \"g\") | .offset]?",
                "[match(\"|(?<=.)\"; \"g\") | .offset]?",
            ],
            [
                "\"\"", "\"a\"", "\"b\"", "\"aa\"", "\"ab\"", "\"ba\"",
                "\"é\"", "\"😀\"", "\"é😀\"", "\"aé😀b\"", "\"a\\nb\"", "\"á\"",
            ]),
        new(
            "regex-replacement-streams",
            [
                "sub(\"a\"; \"X\", \"Y\")?",
                "gsub(\"a\"; \"X\", \"Y\")?",
                "sub(\"(?<x>a)?b\"; (.x // \"_\"))?",
                "gsub(\"(?<x>a)?b\"; (.x // \"_\"))?",
                "gsub(\"(?<x>a*)\"; \"<\\(.x)>\")?",
                "gsub(\"\"; \"_\")?",
                "split(\"\"; \"\")?",
                "[splits(\"\"; \"\")]?",
                "split(\"(?=a)\"; \"\")?",
                "[splits(\"(?<=a)\"; \"\")]?",
                "[scan(\"(?<x>a)|(b)\")]?",
                "[scan(\"(?<x>a*)\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"ba\"", "\"aba\"",
                "\"bbb\"", "\"aaabbb\"", "\"A,b z\"", "\"é\"", "\"😀\"", "\"aé😀b\"",
            ]),
        new(
            "regex-newline-options",
            [
                "[scan(\"^a\")]?",
                "[scan(\"a$\")]?",
                "[scan(\"^a\"; \"s\")]?",
                "[scan(\"a$\"; \"s\")]?",
                "[scan(\"^a\"; \"m\")]?",
                "[scan(\"a$\"; \"m\")]?",
                "[scan(\"^a\"; \"p\")]?",
                "[scan(\"a$\"; \"p\")]?",
                "[scan(\"\\\\A.a\\\\z\"; \"m\")]?",
                "[scan(\"\\\\A.a\\\\Z\"; \"m\")]?",
                "[scan(\"\\\\R\")]?",
                "[scan(\"\\\\N+\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"a\\n\"", "\"\\na\"", "\"a\\nb\"", "\"b\\na\"",
                "\"a\\r\\n\"", "\"a\\rb\"", "\"a\\u0085b\"", "\"a\\u2028b\"", "\"é\\n😀\"", "\"\\r\\n\"",
            ]),
        new(
            "regex-lookaround-backref",
            [
                "[scan(\"(?<=a)b\")]?",
                "[scan(\"(?<!a)b\")]?",
                "[scan(\"(?<=ab|cd)e\")]?",
                "[scan(\"(?<!ab|cd)e\")]?",
                "[scan(\"(?=(a+))a\")]?",
                "[scan(\"(a+)\\\\1\")]?",
                "[scan(\"(.)\\\\1\"; \"i\")]?",
                "[scan(\"(?<x>a)?b\\\\k<x>\")]?",
                "[scan(\"(?<x>a)(?<x>b)\\\\k<x>\")]?",
                "[scan(\"(a)(b)\\\\g{-1}\")]?",
                "[scan(\"(?=(?<x>a))\\\\k<x>\")]?",
                "[scan(\"(?<=(a))\\\\1\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"b\"", "\"ab\"", "\"abb\"", "\"aba\"",
                "\"abe cde\"", "\"ace\"", "\"aaaa\"", "\"AaAA\"", "\"éé😀😀\"", "\"baab\"",
            ]),
        new(
            "regex-oniguruma-fallbacks",
            [
                "[scan(\"(a)(?1)\")]?",
                "[scan(\"(?<x>a)(?&x)\")]?",
                "[scan(\"(?<x>a)\\\\g<x>\")]?",
                "match(\"a\\\\Kb\"; \"g\")?",
                "[scan(\"(?~a)\")]?",
                "[scan(\"(?{x})a\")]?",
                "[scan(\"(*FAIL)a\")]?",
                "[scan(\"(?(?{....})123|456)\")]?",
                "[scan(\"(?(*FAIL)123|456)\")]?",
                "[scan(\"\\\\X\")]?",
                "[match(\"\\\\y\"; \"g\") | .offset]?",
                "[match(\"\\\\Y\"; \"g\") | .offset]?",
                "[scan(\"\\\\p{Emoji}+\")]?",
                "[scan(\"\\\\p{Extended_Pictographic}+\")]?",
                "[scan(\"\\\\p{emoji}+\")]?",
                "[scan(\"\\\\p{Emoji_Component}+\")]?",
                "[scan(\"\\\\p{Emoji_Modifier}+\")]?",
                "[scan(\"\\\\p{Emoji_Modifier_Base}+\")]?",
                "[scan(\"\\\\p{Emoji_Presentation}+\")]?",
                "[scan(\"(?<x>a|b\\\\g<x>c)\")]?",
                "[scan(\"(a)\\\\g<-1>(b)\")]?",
                "[scan(\"^\\\\X$\")]?",
                "test(\".\\\\Y.\")?",
                "[match(\"(?<x>a)\\\\K(?<y>b)\") | [.offset,.length,.string,.captures]]?",
                "sub(\"a\\\\Kb\"; \"X\")?",
                "gsub(\"a\\\\Kb\"; \"X\")?",
                "[splits(\"a\\\\Kb\")]?",
            ],
            [
                "\"\"", "\"a\"", "\"aa\"", "\"ab\"", "\"ba\"", "\"bbb\"",
                "\"á\"", "\"é\"", "\"😀\"", "\"a😀b\"", "\"\\r\\n\"", "\"👩‍💻!\"",
                "\"bbacc\"", "\"🇺🇳👍🏽\"", "\"각\"", "\"நி\"", "\"กำ\"", "\"؀a\"",
                "\"〰̂‍⭕\"", "\"abxab\"", "\"⌁◀★⭐⬀⬅🀀🇦🏽\"", "\"#‍⃣️🇦🏽🦰a\"",
                "\"123\"", "\"456\"",
            ]),
        new(
            "regex-absent-ranges",
            [
                "\"123456789\" | match(\"(?~|78|\\\\d*)\")",
                "\"abcdedeabcfdefabc\" | match(\"(?~|def|(?:abc|de|f){0,100})\")",
                "\"ccc\\ndab\" | match(\"(?~|ab|\\\\O{2,10})\")",
                "\"ab\" | match(\"(?~|ab|\\\\O{2,10})\")?",
                "\"aaaaaa\" | match(\"(a)(?~|bb|(?:a\\\\1)*)\")",
                "\"abababacabab\" | match(\"(b|c)(?~|abac|(?:a\\\\1)*)\")",
                "\"aaaaaabc\" | match(\"(?~|abc)a*z|aaaaaabc\")",
                "\"a\" | match(\"(?~|a)a\")?",
                "\"a\" | match(\"(?~|a)(?~|)a\")",
                "\"bbbbbbbbbbbbbbbbbbbba\" | match(\"(?~|a).*(?~|)a\")",
                "\"aaaaxyzaaapqrabc\" | match(\"(?~|abc).*(xyz|pqr)(?~|)abc\")",
                "\"aaaaxyzaaaabcpqrabc\" | match(\"(?~|abc).*(xyz|pqr)(?~|)abc\")",
                "\"ab\" | match(\"(?~|a)((?~|)c|ab|a|)\")",
                "\"aaab\" | match(\"(?~|(a)b|(x)?a*)\")",
            ],
            ["null"]),
        new(
            "regex-callout-events",
            [
                "\"abcbaaccaaa\" | match(\"(?:[ab]|(*MAX{2}).)*\") | {offset,length,string}",
                "\"abababcdab\" | match(\"(?:(*COUNT[AB]{X})[ab]|(*COUNT[CD]{X})[cd])*(*CMP{AB,<,CD})\") | {offset,length,string}",
                "\"aaaa\" | match(\"(?:(*COUNT[A]{X})a)*(*CMP{A,==,3})\") | {offset,length,string}",
                "\"aaccc\" | match(\"(?:(*COUNT[T]{X})a)*(?:(*MAX{T})c)*\") | {offset,length,string}",
                "\"a\" | test(\"z(*ERROR)|a\")",
                "\"a\" | try test(\"a(*ERROR)|a\") catch .",
                "\"a\" | try test(\"a(*ERROR)z|a\") catch .",
                "\"a\" | [match(\"a(*MISMATCH)|a\")]",
                "\"b\" | test(\"(?(*MISMATCH)a|b)\")",
                "\"b\" | test(\"(?(*FAIL)a|b)\")",
                "\"b\" | test(\"(?(*CMP{2,<,1})a|b)\")",
                "\"a\" | test(\"(?(*CMP{1,<,2})a|b)\")",
                "\"b\" | test(\"(?(*MAX{0})a|b)\")",
                "\"a\" | test(\"(?(*MAX{1})a|b)\")",
                "\"aac\" | [match(\"aa(*SKIP)b|ac\") | {offset,length,string}]",
                "\"aaab\" | match(\"aa(*SKIP)b|a\") | {offset,length,string}",
                "\"aacaac\" | [scan(\"aa(*SKIP)c|ac\")]",
                "\"aaaXXXX\" | match(\"aaa(*SKIP)|aaX+\";\"l\") | {offset,length,string}",
                "\"a\" | test(\"a|z(*COUNT{Q})\")",
                "\"a\" | test(\"(*COUNT[A]{X})(*CMP{A,==,A})a\")",
                "\"a\" | test(\"(*COUNT[A]{X})(*CMP{A,<=,A})a\")",
                "\"a\" | test(\"(*SKIP[T])(*CMP{T,==,0})a\")",
                "\"a\" | test(\"(*CMP{E,==,0})a|(*ERROR[E])\")",
                "\"\" | test(\"(*CMP[C]{1,<,2})(*CMP{C,==,2})\")",
                "\"a\" | test(\"(*MAX{513})a\")",
                "\"a\" | try test(\"a(*ERROR{1})\") catch .",
                "\"a\" | try test(\"a(*ERROR{-4294967299})\") catch .",
                "\"ab\" | test(\"^(?:(?(*MAX{1})a|b))+$\")",
                "\"aa\" | test(\"^(?:(?(*MAX{1})a|b))+$\")",
                "\"aaab\" | match(\"aa(*MISMATCH)b|a+\";\"l\") | {offset,length,string}",
                "\"aba\" | \"(*COUNT[T]{>})z|(*CMP{T,==,1})(?<v>a)\" as $p | {test:test($p),matches:[match($p;\"g\")|{offset,length,string,captures}],capture:capture($p),scan:[scan($p)],splits:[splits($p)],sub:sub($p;\"X\"),gsub:gsub($p;\"X\")}",
                "\"aaaa\" | match(\"(?:(*COUNT[A]{>})a)*(*CMP{A,==,3})\") | {offset,length,string}",
                "\"aaaa\" | match(\"(?:(*COUNT[A]{<})a)*(*CMP{A,==,1})\") | {offset,length,string}",
                "\"ba\" | test(\".(*TOTAL_COUNT[T])z|a(*CMP{T,==,2})\")",
                "\"b\" | test(\"(?<x>(*MAX{1,>})b)c|\\\\g<x>\")",
                "(\"a\"*600) | test(\"(?:(*COUNT[A]{X})a)*(*CMP{A,==,600})\")",
                "(\"a\"*5000) as $s | $s | match($s + \"(*COUNT[T]{>})(*CMP{T,==,1})\") | {offset,length,string:(.string|length)}",
                "(\"b\"*19 + \"a\" + \"c\"*19) | test(\"\\\\A(?<x>a|b\\\\g<x>c)\\\\z\")",
                "(\"b\"*20 + \"a\" + \"c\"*20) | test(\"\\\\A(?<x>a|b\\\\g<x>c)\\\\z\")",
                "(\"b\"*20 + \"a\" + \"c\"*20) | match(\"(?<x>a|b\\\\g<x>c)(*COUNT[T]{X})(*CMP{T,==,1})\") | {offset,length}",
                "(\"b\"*19 + \"a\" + \"c\"*19) | test(\"\\\\A(?:(?<x>a|b\\\\g<y>c)(?<y>a|b\\\\g<x>c)|\\\\g<x>)(*COUNT[T]{X})(*CMP{T,==,1})\\\\z\")",
                "(\"b\"*20 + \"a\" + \"c\"*20) | test(\"\\\\A(?:(?<x>a|b\\\\g<y>c)(?<y>a|b\\\\g<x>c)|\\\\g<x>)(*COUNT[T]{X})(*CMP{T,==,1})\\\\z\")",
                "(\"(?:\"*511 + \"a\" + \")\"*511 + \"(*COUNT[T]{X})(*CMP{T,==,1})\") as $re | \"a\" | test($re)",
                "(\"(?:\"*512 + \"a\" + \")\"*512 + \"(*COUNT[T]{X})(*CMP{T,==,1})\") as $re | try (\"a\" | test($re)) catch .",
                "(\"a\"*10000) | test(\"\\\\Aa*(*COUNT[T]{X})(*CMP{T,==,1})\\\\z\")",
                "(\"a\"*10000) | test(\"\\\\Aa{10000}(*COUNT[T]{X})(*CMP{T,==,1})\\\\z\")",
                "(\"a\"*10000) | test(\"\\\\Aa*(*COUNT[A]{>})b|a{10000}(*COUNT[B]{>})(*CMP{A,==,10001})(*CMP{B,==,1})\\\\z\")",
                "(\"a\"*5000) | test(\"\\\\A(?:(*MAX{5000})a)*\\\\z\")",
                "(\"a\"*5001) | test(\"\\\\A(?:(*MAX{5000})a)*\\\\z\")",
                "(\"a\"*65535 + \"b\") | test(\"(?<=a{65535})b\")",
                "try ((\"a\"*65536 + \"b\") | test(\"(?<=a{65536})b\")) catch .",
                "\"abbx\" | test(\"(?<=\\\\Qab\\\\E{2})x\")",
                "(\"(?<=\\\\Q\" + \"a\"*65536 + \"\\\\E)b\") as $re | try (\"b\" | test($re)) catch .",
                "\"b\" | match(\"(?(*FAIL)(a)|(b))\") | [.captures[].string]",
                "\"b\" | match(\"z(*ERROR)(a)|(b)\") | [.captures[].string]",
                "\"bb\" | test(\"(?(*FAIL)(a)|(b))\\\\2\")",
                "\"aaa\" | test(\"(?(*COUNT)(a)|(b))(a)\\\\2\")",
                "[(\"(*ERROR)\"|test(\"\\\\Q(*ERROR)\\\\E\")),(\"a\"|test(\"(?#(*ERROR)a\")),(\"a\"|test(\"# (*ERROR)\\na\";\"x\"))]",
                "[try (\"\"|test(\"(*ERROR)\";\"n\")) catch .,(\"a\"|test(\"a|(*ERROR)\";\"n\"))]",
                "[try (\"\"|test(\"(*ERROR{+})\")) catch .,(\"\"|test(\"(*MAX{+})\")),(\"\"|test(\"(*CMP{+,==,-})\"))]",
                "[try (\"\"|test(\"(*ERROR{-6})\")) catch .,try (\"\"|test(\"(*ERROR{-15})\")) catch .,try (\"\"|test(\"(*ERROR{-217})\")) catch .]",
                "[(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})a\";\"i\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1}).\";\"m\")),(\"\\na\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})^a\";\"s\")),(\"a\"|test(\"(*COUNT[T]{>}) z | (*CMP{T,==,1}) a\";\"x\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1}).\";\"p\"))]",
                "\"a\" | [match(\"a|a(*MISMATCH)\";\"l\") | {offset,length,string}]",
                "\"ba\" | [(try match(\"(*TOTAL_COUNT[T]{>})z|(*CMP{T,==,1})a\") catch .),(try match(\"(*TOTAL_COUNT[T]{>})z|(*CMP{T,==,2})a\") catch .)]",
                "\"😀a\" | match(\"(*TOTAL_COUNT[T]{>})z|(*CMP{T,==,1})a\") | {offset,length,string}",
                "[try (\"\"|test(\"(*ERROR)(\")) catch .,try (\"\"|test(\"(*MISMATCH)(\")) catch .,try (\"\"|test(\"(*ERROR)\\\\9\")) catch .]",
                "[try (\"\"|test(\"(*ERROR)[\")) catch .,try (\"\"|test(\"(*ERROR)(?<x>a\")) catch .,try (\"\"|test(\"(*ERROR)\\\\p{NoSuch}\")) catch .,try (\"\"|test(\"(*ERROR)(?q)\")) catch .,try (\"\"|test(\"(*ERROR)*\")) catch .,try (\"\"|test(\"(*ERROR)a{2,1}\")) catch .,try (\"\"|test(\"(*ERROR)\\\\k<no>\")) catch .]",
                "[(\"a\"|test(\"# hidden\\r(*COUNT{QQ})\";\"x\")),(try (\"\"|test(\"(?#foo\\\\)bar)(*ERROR)\")) catch .),(try (\"\\b\"|test(\"\\\\10(*ERROR)\")) catch .),(try (\"S\"|test(\"\\\\123(*ERROR)\")) catch .),(\"a\"|test(\"\\\\99(*ERROR)\"))]",
                "[try (\"\"|test(\"(*COUNT[T])(*COUNT[T])(\")) catch .,try (\"\"|test(\"\\\\p{NoSuch}(*COUNT[T])(*COUNT[T])\")) catch .,try (\"\"|test(\"((*MAX{NOPE})\")) catch .,(\"a\"|test(\"(*MAX{T})(*COUNT[T])a\"))]",
                "\"x\\na\" | [[1,2,3,4][] as $n | [match(\"(*TOTAL_COUNT[T]{>})^a(*CMP{T,==,\\($n)})\") | {offset,length,string}]]",
                "[(\"axab\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})ab(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"abab\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})ab(*CMP{T,==,\\($n)})\")|{offset,length,string}])]",
                "[(\"bba\"|[1,2,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[a](*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"bba\"|[1,2,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[^b](*CMP{T,==,\\($n)})\")|{offset,length,string}])]",
                "[(\"bba\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(?:x|)a(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"xxab\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})x?ab(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"yxxab\"|[1,2,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})x{0,2}ab(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"yyxxab\"|[3,4,5][] as $n|[match(\"(*TOTAL_COUNT[T]{>})x*ab(*CMP{T,==,\\($n)})\")|{offset,length,string}])]",
                "[(\"axac\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(ab|ac)(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"axabd\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(abc|abd)(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"axcd\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(ab|cd)(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"xxAB\"|[1,2,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})ab(*CMP{T,==,\\($n)})\";\"i\")|{offset,length,string}])]",
                "\"xba\" | [(test(\"x(*TOTAL_COUNT[T]{>})z|(*CMP{T,==,0})a\")),(test(\"x(*TOTAL_COUNT[T]{>})z|(*CMP{T,==,1})a\"))]",
                "\"😀a\" | match(\"(*COUNT[T]{>})\\\\x{1F600}|(*CMP{T,==,1})a\") | {offset,length,string}",
                "[(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\p{L}\")),(\"1\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\P{L}\")),(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[[:alpha:]]\"))]",
                "[(\"😀\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\X\")),(\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\y\")),(\"ab\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\Y\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\R\")),(\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\N\")),(\"😀\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\O\"))]",
                "[try (\"ab\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})a\\\\Kb\")|{offset,length,string}) catch .,try (\"a\"|test(\"\\\\Qa\\\\E(*ERROR)\")) catch .,try (\"b\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?~a)\")) catch .]",
                "[try (\"ab\"|test(\"(?<=a)(*COUNT[T]{>})z|(?<=a)(*CMP{T,==,1})b\")) catch .,try (\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?i:a)\")) catch .,try (\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\\\ba\\\\b\")) catch .]",
                "\"aa\" | match(\"(?<x>a(*COUNT[T]{>}))\\\\g<x>(*CMP{T,==,2})\") | {offset,length,string,captures}",
                "[try (\"𐐨\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[𐐨]\")|{offset,length,string}) catch .,try (\"𐐨\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[𐐀-𐐿]\")|{offset,length,string}) catch .]",
                "[(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[a]\";\"i\")),(\"B\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[a-c]\";\"i\")),(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[^a]\";\"i\"))]",
                "[(\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})\\u000Ba\";\"x\")),(\"aaa\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})a *\";\"x\")|.string),(\"aa\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})a {2}\";\"x\")|.string),(\"aa\"|match(\"(*COUNT[T]{>})z|(*CMP{T,==,1})a{2} ?\";\"x\")|.string)]",
                "[(\"!K\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})k(*CMP{T,==,\\($n)})\";\"i\")|.offset]),(\"!S\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})s(*CMP{T,==,\\($n)})\";\"i\")|.offset]),(\"bba\"|[1,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[aé](*CMP{T,==,\\($n)})\")|.offset]),(\"bb1\"|[1,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})\\\\d(*CMP{T,==,\\($n)})\")|.offset])]",
                "[(\"😀a\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>}).?a(*CMP{T,==,\\($n)})\")|.offset]),(\"😀a\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})é?a(*CMP{T,==,\\($n)})\")|.offset]),(\"éa\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})é?a(*CMP{T,==,\\($n)})\")|.offset]),(\"bbbba\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[x]?a(*CMP{T,==,\\($n)})\")|.offset]),(\"bbbbba\"|[4,5][] as $n|[match(\"(*TOTAL_COUNT[T]{>})\\\\w?a(*CMP{T,==,\\($n)})\")|.offset])]",
                "[(\"é\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})é\")),(\"😀\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})😀\")),(\"éé\"|test(\"(é)(*COUNT[T]{>})\\\\1(*CMP{T,==,1})\")),(\"😀😀\"|test(\"(?<x>😀)(*COUNT[T]{>})\\\\k<x>(*CMP{T,==,1})\")),(\"SSSS\"|test(\"(?<x>ß)(*COUNT[T]{>})\\\\k<x>(*CMP{T,==,1})\";\"i\")),(\"SS\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[ß]\";\"i\")),(\"𐐨\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})[𐐀]\";\"i\"))]",
                "[(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?i)a\")),(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?i:a)\")),(\"\\na\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?m)^a\")),(\"\\na\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?m:^a)\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?s).\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?s:.)\")),(\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?x) a\")),(\"a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?x: a )\")),(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?-i)a\";\"i\")),(\"A\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?-i:a)\";\"i\")),(\"\\na\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?m)(?-m)^a\")),(\"\\na\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?m)(?-m:^a)\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?s)(?-s).\")),(\"\\n\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?s)(?-s:.)\")),(\" a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?x)(?-x) a\")),(\" a\"|test(\"(*COUNT[T]{>})z|(*CMP{T,==,1})(?x)(?-x: )a\"))]",
                "[(\"!A\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(?i)a(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"!A\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(?i:a)(*CMP{T,==,\\($n)})\")|{offset,length,string}]),(\"!a\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(?-i)a(*CMP{T,==,\\($n)})\";\"i\")|{offset,length,string}]),(\"!a\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})(?-i:a)(*CMP{T,==,\\($n)})\";\"i\")|{offset,length,string}])]",
                "\"x\\nyEND\" | match(\"(?~END)\") | {offset,length,string,captures}",
                "\"123456789\" | match(\"(?~|78|\\\\d*)\") | {offset,length,string,captures}",
                "\"aaaaaabc\" | match(\"(?~|abc)a*z|aaaaaabc\") | {offset,length,string,captures}",
                "\"a\" | match(\"(?~|a)(?~|)a\") | {offset,length,string,captures}",
                "\"aaab\" | match(\"(?~b)a+b\") | {offset,length,string,captures}",
                "\"ba\" | match(\"\\\\A(?~(?:(*COUNT[A]{>})(?<d>a)|(*COUNT[B]{>})a))(*CMP{A,==,2})(*CMP{B,==,2})\") | {offset,length,string,captures}",
                "\"xab\" | match(\"(?<=(a)(*COUNT[T]{X}))b(*CMP{T,==,1})\") | {offset,length,string,captures}",
                "try (\"abc\" | match(\"(?<=a|bc)c\")) catch .",
                "try (\"abbc\" | match(\"(?<=ab+)c\")) catch .",
                "try (\"xb\" | match(\"(?<!(a))b\")) catch .",
                "\"axb\" | match(\"(?<!a(*COUNT[X]{X})(*COUNT[P]{>})c)b(*CMP{X,==,0})(*CMP{P,==,1})\") | {offset,length,string,captures}",
                "\"ab\" | match(\"(?<=\\\\K(a))b\") | {offset,length,string,captures}",
                "\"ab\" | match(\"(?:a\\\\Kc|a)b\") | {offset,length,string,captures}",
                "\"ab\" | match(\"(?=ab\\\\K)a\") | {offset,length,string,captures}",
                "\"abc\" | match(\"(?:ab|a\\\\Kbc)\";\"l\") | {offset,length,string,captures}",
                "[\"(?{})a\",\"(?{opaque})a\",\"(?{é雪😀})a\",\"(?{(*FAIL)})a\",\"(?{x}>)a\",\"(?{x}X)a\",\"(?{x}<)a\",\"(?{{a}b}})a\",\"(?{{{a}b}}})a\",\"(?{{a\\\\}b}})a\",\"(?{\\\\K[not-a-class]#(*ERROR)})a\"] | map(. as $p | \"a\" | test($p))",
                "[(\"a\"|test(\"(?{x}[T])(*CMP{T,==,0})a\")),(\"a\"|test(\"(?{x}[T])(*CMP{T,==,1})a\")),(\"a\"|test(\"(*MAX{T})(?{x}[T])a\")),try (\"a\"|test(\"(?{x}[T])(?{y}[T])a\")) catch .,try (\"a\"|test(\"(?{x}[T])(*COUNT[T])a\")) catch .]",
                "[(\"a\"|test(\"(?(?{x})a|b)\")),(\"b\"|test(\"(?(?{x})a|b)\")),(\"a\"|test(\"(?(?{x}<)a|b)\")),(\"a\"|test(\"(?=(?{x})a)a\")),(\"a\"|test(\"(?!(?{x})a)a\")),(\"ac\"|test(\"(?:a(?{x}X)b|a)c\")),(\"a\"|test(\"(?{{x}})(*COUNT[T]{>})z|(*CMP{T,==,1})(?(?{y})a|b)\"))]",
                "[\"(?{\",\"(?{x\",\"(?{{x})\",\"(?{x}\",\"(?{x}[\",\"(?{x}[T\",\"(?{x}[_\",\"(?{x}[1\",\"(?{x}[])\",\"(?{x}[1T])\",\"(?{x}[é])\",\"(?{x}+)\",\"(?{x}-)\",\"(?{x}Q)\",\"(?{x}XX)\",\"(?{a\\\\}b})\",\"(?(?{x}))\"] | map(. as $p | try (\"a\" | test($p)) catch .)",
                "[\"(?{x})*\",\"(?{x})+\",\"(?{x})?\",\"(?{x}){2}\",\"(?{x}) *\",\"(?{x}) # comment\\n+\"] | map(. as $p | try (\"a\" | test($p;\"x\")) catch .)",
                "\"aba\" | \"(?{opaque})(?<v>a)\" as $p | {test:test($p),matches:[match($p;\"g\")|{offset,length,string,captures}],capture:capture($p),scan:[scan(\"(?{opaque})a\")],splits:[splits(\"(?{opaque})a\")],sub:sub(\"(?{opaque})a\";\"X\"),gsub:gsub(\"(?{opaque})a\";\"X\")}",
                ],
            ["null"]),
        new(
            "regex-subcalls-conditionals",
            [
                "\"bbacc\" | match(\"a|b(?0)c\")",
                "\"bbacc\" | match(\"a|b\\\\g<0>c\")",
                "\"bbacc\" | match(\"a|b\\\\g'0'c\")",
                "\"abb\" | match(\"(a)(?+1)(b)\")",
                "\"abb\" | match(\"(a)\\\\g<+1>(b)\")",
                "\"abb\" | match(\"(a)\\\\g'+1'(b)\")",
                "[\"ab\",\"ac\",\"c\"] | map(test(\"\\\\A(?<x>a)?(?(<x>)b|c)\\\\z\"))",
                "[\"ab\",\"ac\",\"c\"] | map(test(\"\\\\A(?<x>a)?(?('x')b|c)\\\\z\"))",
                "[\"ac\",\"bc\",\"ad\",\"bd\"] | map(test(\"^(?:(?<x>a)|(?<x>b))(?(<x>)c|d)$\"))",
                "[\"ab\",\"ac\",\"c\"] | map(test(\"\\\\A(a)?(?(-1)b|c)\\\\z\"))",
                "[\"ab\",\"c\",\"ac\"] | map(test(\"\\\\A(?(a)b|c)\\\\z\"))",
                "[\"abc\",\"abd\",\"d\"] | map(test(\"^(?(ab)c|d)$\"))",
                "[\"ac\",\"bc\",\"d\"] | map(test(\"^(?(a|b)c|d)$\"))",
                "\"ab\" | match(\"^(?((a))b|c)$\")",
                "[\"b\",\"c\"] | map(test(\"^(?(a*)b|c)$\"))",
                "\"a\" | test(\"^(?(a)b|a)$\")",
                "\"ab\" | match(\"\\\\A(?(a)b|c)\\\\z\")",
                "\"ab\" | match(\"(?<x>a)(?x)b\")",
                "\"ab\" | try match(\"(?<x>a)(?<x>b)\\\\g<x>\") catch .",
                "\"ab\" | try match(\"(?<x>a)(?<x>b)\\\\g'x'\") catch .",
                "\"ab\" | try match(\"(?<x>a)(?<x>b)(?&x)\") catch .",
                "\"ab\" | try match(\"(?<x>a)(?P>x)\") catch .",
            ],
            ["null"]),
        new(
            "regex-counted-grammar-closure",
            [
                "[(\"aa\"|test(\"\\\\A(a)(?1)\\\\K\\\\z\")),(\"abb\"|test(\"\\\\A(a)(?+1)(b)\\\\K\\\\z\")),(\"aa\"|test(\"\\\\A(a)\\\\g<-1>\\\\K\\\\z\")),(\"aa\"|test(\"\\\\A(?<x>a)(?&x)\\\\K\\\\z\"))]",
                "[(\"aa\"|test(\"\\\\A(a)\\\\k<1>\\\\K\\\\z\")),(\"aa\"|test(\"\\\\A(a)\\\\k<-1>\\\\K\\\\z\"))]",
                "[(\"aa\"|test(\"\\\\A(?<愚か>a)\\\\k<愚か>\\\\K\\\\z\")),(\"abb\"|test(\"\\\\A(?<x>a)(?<x>b)\\\\k<x>\\\\K\\\\z\")),(\"aba\"|test(\"\\\\A(?<x>a)(?<x>b)\\\\k<x>\\\\K\\\\z\"))]",
                "[\"a\",\"\",\"ab\",\"c\",\"d\"] | map(. as $s | [($s|test(\"\\\\A(a)?(?(1))\\\\K\\\\z\")),($s|test(\"\\\\A(?()a|b)\\\\K\\\\z\")),($s|test(\"\\\\A(?(a)b|c|d)\\\\K\\\\z\"))])",
                "[\"b\",\"a\",\"ba\"] | map(test(\"\\\\A(?~|(?~a)|b)\\\\K\\\\z\"))",
                "[(\"Q\"|test(\"\\\\A[\\\\Q]\\\\K\\\\z\")),(\"R\"|test(\"\\\\A[\\\\R]\\\\K\\\\z\")),(\"A\"|test(\"\\\\A[\\\\A]\\\\K\\\\z\")),(\"X\"|test(\"\\\\A[\\\\X]\\\\K\\\\z\"))]",
                "[((([7,27,12,127]|implode))|test(\"\\\\A\\\\a\\\\e\\\\f\\\\c?\\\\K\\\\z\")),(([0]|implode)|test(\"\\\\A\\\\c😀\\\\K\\\\z\")),(([10]|implode)|test(\"\\\\A\\\\c\\\\n\\\\K\\\\z\"))]",
                "try (\"x\"|test(\"\\\\K\\\\c\")) catch .",
                "\"abc\" | [match(\"\\\\G\\\\K.\";\"g\")|.string]",
                "[\"ab\",\"aab\",\"b\"] | map([test(\"(?<=a+)b\\\\K\"),test(\"(?<=a*)b\\\\K\")])",
                "[(\"a\"|test(\"\\\\A(a)(?<=\\\\k<1>)\\\\K\\\\z\")),(\"a\"|test(\"\\\\A(?<x>a)(?<=\\\\g<x>)\\\\K\\\\z\")),(\"ab\"|test(\"\\\\Aa(?<=(?~a))b\\\\K\\\\z\")),try (\"b\"|test(\"(?<=(?~|a))b\\\\K\")) catch .]",
                "[(\"bbacca\"|test(\"\\\\A(a|b\\\\g<1>c)\\\\k<1+3>\\\\K\\\\z\")),(\"bbacca\"|test(\"\\\\A(?<x>a|b\\\\g<x>c)\\\\k<x+3>\\\\K\\\\z\")),(\"bbacca\"|test(\"\\\\A(a|b\\\\g<1>c)(?(1+3)a|x)\\\\K\\\\z\"))]",
            ],
            ["null"]),
        new(
            "regex-scalar-character-classes",
            [
                "\"😀\" | test(\"[^a]\")",
                "\"a\" | test(\"[^a]\")",
                "\"😀\" | test(\"[😀]\")",
                "\"😀\" | test(\"[😀-🙏]\")",
                "\"𐐀\" | test(\"[\\\\w]\")",
                "\"𐐀\" | test(\"[\\\\p{Lu}]\")",
                "\"𐐨\" | test(\"[\\\\p{Lu}]\")",
                "\"😀\" | test(\"[\\\\p{Emoji}]\")",
                "\"⌁\" | test(\"[\\\\p{Emoji}]\")",
                "\" \" | test(\"[x[:graph:]]\")",
                "\"\\n\" | test(\"[x[:print:]]\")",
                "\"𐐀\" | test(\"[_[:alpha:]]\")",
                "\"a\" | test(\"[0[:^digit:]]\")",
                "\"0\" | test(\"[0[:^digit:]]\")",
                "\"0\" | test(\"[a[:^digit:]]\")",
                "\"😀 \\n\" | [scan(\"\\\\S+\")]",
                "\"b]\" | [scan(\"[a-z&&[^aeiou]]\")]",
                "\"SS\" | test(\"^[😀ß]$\"; \"i\")",
                "\"FFI\" | test(\"^[😀ﬃ]$\"; \"i\")",
                "\"𐐨\" | test(\"^[😀𐐀]$\"; \"i\")",
                "\"𐐀\" | test(\"^[😀𐐨]$\"; \"i\")",
                "null | try (\"a\" | test(\"[a-\\\\w]\")) catch .",
                "null | try (\"a\" | test(\"[a-\\\\p{L}]\")) catch .",
                "null | try (\"a\" | test(\"[a-[:alpha:]]\")) catch .",
                "null | try (\"a\" | test(\"[😀-\\\\p{Emoji}]\")) catch .",
                "null | try (\"a\" | test(\"[😀--🙏]\")) catch .",
                "null | try (\"a\" | test(\"[🙏-😀]\")) catch .",
            ],
            ["null"]),
        new(
            "regex-oniguruma-residual-family-b",
            [
                "[(\"u\"|test(\"\\\\u\")),(\"C\"|test(\"\\\\C\")),(\"P\"|test(\"\\\\P\")),(\"1\"|test(\"\\\\P{L}\"))]",
                "[(\"u\"|test(\"[\\\\u]\")),(\"0\"|test(\"[\\\\u0041]\")),(\"A\"|test(\"[\\\\u0041]\"))]",
                "\"AB\" | match(\"\\\\x{41 42}\") | .string",
                "\"AB\" | match(\"\\\\o{101 102}\") | .string",
                "\"😀A\" | match(\"\\\\x{1F600 41}\") | .string",
                "\"A😀B\" | [scan(\"[\\\\x{41 1F600}]\")]",
                "\"A😀B\" | [scan(\"[\\\\o{101 373000}]\")]",
                "[(\"SS\"|test(\"(?i)ß\")),(\"SS\"|test(\"(?-i)ß\";\"i\")),(\"ﬃ\"|test(\"(?i)ffi\")),(\"FFI\"|test(\"(?-i:ffi)\";\"i\"))]",
                "\"a\" | try test(\"(?=a)*\") catch .",
                "\"a\" | try test(\"^*\") catch .",
                "\"abcd\" | try test(\"(?<=a|bc)d\") catch .",
                "[(\"abd\"|test(\"(?<=ab|cd)d\")),(\"ab\"|test(\"(?<=a*)b\"))]",
                "[(\"AB\"|match(\"\\\\x{41\\n42}\").string),(\"AB\"|match(\"\\\\o{101\\n102}\").string)]",
                "[(\"A😀\"|test(\"\\\\x{D800}\")),(\"A😀\"|test(\"\\\\x{110000}\")),(\"A😀\"|test(\"\\\\o{4777777}\"))]",
                "[(\"A\"|test(\"[\\\\x{41 110000}]\")),(\"A\"|test(\"[^\\\\x{110000}]\")),(\"😀\"|test(\"[^\\\\x{110000}]\"))]",
                "\"ABCDEPP\" | [[scan(\"[\\\\x{41-43 50}]\")],[scan(\"[\\\\o{101 - 103}]\")]]",
                "[(\"x\"|test(\"\\\\x\")),(\"x{}\"|test(\"\\\\x{}\")),(\"x{ 41}\"|test(\"\\\\x{ 41}\")),(\"o101\"|test(\"\\\\o101\"))]",
                "[(try (\"A\"|test(\"\\\\x{41\\t42}\")) catch .),(try (\"A\"|test(\"\\\\o{101 }\")) catch .),(try (\"A\"|test(\"\\\\x{41,42}\")) catch .)]",
                "[(try (\"A\"|test(\"\\\\x{140000}\")) catch .),(try (\"A\"|test(\"[\\\\x{200000}]\")) catch .),(try (\"A\"|test(\"[\\\\x{43-41}]\")) catch .)]",
                "[(try (\"A\"|test(\"\\\\x{100000000}\")) catch .),(try (\"A\"|test(\"\\\\o{100000000000}\")) catch .),(try (\"A\"|test(\"\\\\o{40000000000}\")) catch .)]",
            ],
            ["null"]),
        new(
            "regex-leveled-backref-absent-lookbehind-boundaries",
            [
                "\"\" | try test(\"\\\\k<>\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1+>\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1->\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1+x>\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1++1>\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1+-1>\") catch .",
                "\"a\" | try test(\"(a)\\\\k'1+'\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1+2147483648>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1-2147483648>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1+2147483647>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1-2147483647>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1+0>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1-0>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<1+00>\") catch .",
                "\"a\" | try test(\"(a)\\\\k<1+\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<2+0>\") catch .",
                "\"aa\" | try test(\"(a)\\\\k<x+0>\") catch .",
                "\"b\" | try test(\"\\\\A(?(0)a|b)\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(2)a|b)(a)?\\\\z\") catch .",
                "\"c\" | try test(\"\\\\A(a)?(?(-2)b|c)\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(-1)a|b)(a)?\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(<>)a|b)\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(<missing>)a|b)\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(2147483648)a|b)\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(1)a|b)(a)?\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(+1)a|b)(a)?\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(2)a|b)(a)?(a)?\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?(<x>)a|b)(?<x>a)?\\\\z\") catch .",
                "\"b\" | try test(\"\\\\A(?('x')a|b)(?<x>a)?\\\\z\") catch .",
                "\"ab\" | try test(\"\\\\A(?<x>a)?(?(<x>)b|c)\\\\z\") catch .",
                "\"c\" | try test(\"\\\\A(?<x>a)?(?(<x>)b|c)\\\\z\") catch .",
                "\"b\" | try test(\"(?<=(?~a))b\") catch .",
                "\"ab\" | try test(\"\\\\Aa(?<=(?~a))b\\\\z\") catch .",
                "\"xb\" | try test(\"(?<=x(?~a))b\") catch .",
                "\"b\" | try test(\"(?<=(?~a){2})b\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b))c\") catch .",
                "\"abc\" | try test(\"(?<=(?~|z|ab))c\") catch .",
                "\"abc\" | try test(\"(?<=(?~|z|a|bc))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b*))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b+))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b?))c\") catch .",
                "\"c\" | try test(\"(?<=(?~|a|b{0}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{0,2}))c\") catch .",
                "\"bbc\" | try test(\"(?<=(?~|a|b{2}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{1,2}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|[bc]*))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|.*))c\") catch .",
                "\"bcc\" | try test(\"(?<=(?~|a|(bc)*))c\") catch .",
                "(\"b\"*65535 + \"c\") | try test(\"(?<=(?~|a|b{65535}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{65536}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{1,65535}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{1,65536}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{65535,}))c\") catch .",
                "\"bc\" | try test(\"(?<=(?~|a|b{65536,}))c\") catch .",
                "\"xb\" | try test(\"(?<!(?~a))b\") catch .",
                "\"xb\" | try test(\"(?<!(?~(a)))b\") catch .",
            ],
            ["null"]),
        new(
            "regex-parser-normalization-closure",
            [
                "{map_optimizer:[(\"bbbba\"|[1,2][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[x]?a(*CMP{T,==,\\($n)})\")|.offset]),(\"bba\"|[1,2,3][] as $n|[match(\"(*TOTAL_COUNT[T]{>})[^b](*CMP{T,==,\\($n)})\")|.offset])]}",
                "{diagnostic_precedence:[try (\"\"|test(\"[\\\\c]\";\"i\")) catch .,try (\"a\"|test(\"(?<a)>a)\";\"i\")) catch .,try (\"a\"|test(\"\\\\g<a)>\";\"im\")) catch .]}",
                "{targetless:[\"{0}\",\"{100001}\",\"{2,1}\",\"(?#c)*\",\"^*\"]|map(. as $p|try(\"\"|test($p))catch .)}",
                "{nested:[(\"éa\"|[match(\"a??*+\";\"g\")|[.offset,.length,.string]]),(\"abab\"|[match(\"(?:ab){1}{0,}?\";\"g\")|[.offset,.length,.string]]),(\"ababb\"|[match(\"\\\\x{61 62}{2}\";\"g\")|[.offset,.length,.string]])]}",
                "{search_start:(\"a\"|{match:[match(\"\\\\G\";\"g\")|[.offset,.length]],scan:[scan(\"\\\\G\")],splits:[splits(\"\\\\G\")],gsub:gsub(\"\\\\G\";\"X\")})}",
                "{nul_ignorecase:(([0]|implode)|test(\"\\u0000\";\"i\"))}",
                "{option_specs:[(\"A\"|test(\"(?i--m:a)\")),(\"A\"|test(\"(?i-m-s)a\")),(\"a\"|test(\"(?--)a\"))]}",
                "{whole_recursion:(try(\"a\"|test(\"a(?R)?\"))catch .)}",
                "{supplementary_properties:[(\"𐐀\"|test(\"\\\\P{C}\")),(\"𐐀\"|test(\"[\\\\p{Assigned}]\")),(\"󰀀\"|test(\"[\\\\p{Other}]\")),(\"󰀀\"|test(\"\\\\P{Cs}\"))]}",
                "{class_source:[(\"[\"|test(\"[&&&&[\\\\S]\")),(\"[\"|test(\"[^&&[é]\")),(\"[b]\"|test(\"\\\\A[[][]&&[^b]]\\\\z\")),(\"a]\"|test(\"\\\\A[a&&[-[b&&]]\\\\z\")),(\"A\"|test(\"[*é\\\\--b]\"))]}",
                "{control_operands:[[8,\"\\\\c(\"],[9,\"\\\\c)\"],[27,\"\\\\c[\"]]|map(. as $x|(([$x[0]]|implode)|test($x[1];\"i\")))}",
                "{numeric_refs:[(\"aa\"|test(\"(a)\\\\k<-1>\")),(\"aba\"|test(\"(a)(b)\\\\k<-2>\")),try(\"a\"|test(\"(a)\\\\g<2>\"))catch .]}",
                "{group_names:[(\"a\"|test(\"(?<a(>a)\")),(\"aa\"|test(\"(?<a[>a)(?&a[)\")),try(\"aa\"|test(\"(?<a[>a)\\\\k<a[>\"))catch .]}",
                "{parse_depth:([1022,1023]|map(. as $n|(\"a\"+(\"*\"*$n)) as $p|try(\"\"|test($p))catch .))}",
                "{repeat_suffix:[(\"\"|test(\"a+?\")),(\"\"|test(\"a+ ?\";\"x\")),(\"\"|test(\"a+(?#c)?\")),(\"aaa\"|match(\"a* ?+\";\"x\")|.string)]}",
                "{class_diagnostics:[try(\"\"|test(\"[]\"))catch .,try(\"\"|test(\"[^]\"))catch .,try(\"!\"|test(\"[[:Punct:]]\"))catch .]}",
            ],
            ["null"]),
        new(
            "regex-unicode-property-catalog",
            RegexUnicodePropertyCorpus.Filters,
            ["null"]),
    ];

    internal static IReadOnlyList<ProbeCase> Generate(int seed, int count)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(count);

        var queues = Groups
            .Select((group, groupIndex) =>
            {
                var combinations = group.Filters
                    .SelectMany(filter => group.Inputs.Select(input => (Filter: filter, Input: input)))
                    .ToList();
                Shuffle(combinations, new Random(unchecked(seed + groupIndex * 7_919)));
                return (Category: group.Category, Combinations: combinations, Index: 0);
            })
            .ToArray();

        if (count > DefaultCount)
        {
            throw new ArgumentOutOfRangeException(nameof(count), "Requested regex corpus exceeds unique case capacity.");
        }

        var cases = new List<ProbeCase>(count);
        var uniquePairs = new HashSet<(string Filter, string Input)>();
        var cursor = Math.Abs(seed % queues.Length);
        while (cases.Count < count)
        {
            var selected = -1;
            for (var offset = 0; offset < queues.Length; offset++)
            {
                var candidate = (cursor + offset) % queues.Length;
                if (queues[candidate].Index < queues[candidate].Combinations.Count)
                {
                    selected = candidate;
                    break;
                }
            }

            if (selected < 0)
            {
                throw new InvalidOperationException("Regex corpus generation exhausted unexpectedly.");
            }

            var queue = queues[selected];
            var combination = queue.Combinations[queue.Index];
            queues[selected] = (queue.Category, queue.Combinations, queue.Index + 1);
            if (uniquePairs.Add(combination))
            {
                cases.Add(new ProbeCase(cases.Count + 1, queue.Category, combination.Filter, combination.Input));
            }

            cursor = (selected + 1) % queues.Length;
        }

        return cases;
    }

    private static void Shuffle(List<(string Filter, string Input)> values, Random random)
    {
        for (var index = values.Count - 1; index > 0; index--)
        {
            var other = random.Next(index + 1);
            (values[index], values[other]) = (values[other], values[index]);
        }
    }

    private sealed record Group(string Category, string[] Filters, string[] Inputs);
}
