#!/usr/bin/env perl

use strict;
use warnings;
use Digest::SHA qw(sha256_hex);
use MIME::Base64 qw(encode_base64);

my $mode = shift(@ARGV) // q{};
my ($upstream_path, $managed_path) = @ARGV;
die "usage: $0 (--check|--write) unicode_egcb_data.c OnigurumaExtendedGraphemeData.cs\n"
    if ($mode ne '--check' && $mode ne '--write') || @ARGV != 2;

my $upstream = slurp($upstream_path);
my $managed = slurp($managed_path);
my $source_sha = sha256_hex($upstream);
my $expected_sha = '21663445ace4f64775506f3fc53332a96e1b2b9f509b63eeb5462913daeb6d73';
die "unexpected unicode_egcb_data.c SHA-256: $source_sha\n"
    if $source_sha ne $expected_sha;
die "unexpected grapheme property version\n"
    if $upstream !~ /^#define GRAPHEME_BREAK_PROPERTY_VERSION\s+160000\s*$/m;

my %type_id = (
    CR => 1,
    LF => 2,
    Control => 3,
    Extend => 4,
    Prepend => 5,
    Regional_Indicator => 6,
    SpacingMark => 7,
    ZWJ => 8,
    L => 13,
    LV => 14,
    LVT => 15,
    T => 16,
    V => 17,
);
my %expected_type_count = (
    CR => 1,
    Control => 19,
    Extend => 376,
    L => 2,
    LF => 1,
    LV => 399,
    LVT => 399,
    Prepend => 16,
    Regional_Indicator => 1,
    SpacingMark => 155,
    T => 2,
    V => 4,
    ZWJ => 1,
);

my @ranges;
my %actual_type_count;
while ($upstream =~ /\{0x([0-9a-f]+), 0x([0-9a-f]+), EGCB_([A-Za-z_]+) \}/g) {
    my ($start, $end, $type) = (hex($1), hex($2), $3);
    die "unknown EGCB type '$type'\n" if !exists($type_id{$type});
    push(@ranges, [$start, $end, $type]);
    $actual_type_count{$type}++;
}
die "expected 1376 EGCB ranges, got " . scalar(@ranges) . "\n"
    if @ranges != 1376;
for my $type (sort keys(%expected_type_count)) {
    my $actual = $actual_type_count{$type} // 0;
    die "expected $expected_type_count{$type} $type ranges, got $actual\n"
        if $actual != $expected_type_count{$type};
}

# Reproduce the checked-in encoding exactly. The regular AC00-D7A3 Hangul
# LV/LVT alternation is intentionally regenerated by the managed decoder.
my $previous_end = -1;
my $encoded = q{};
for my $range (@ranges) {
    my ($start, $end, $type) = @$range;
    next if $start >= 0xac00 && $end <= 0xd7a3;
    $encoded .= encode_unsigned($start - $previous_end - 1);
    $encoded .= encode_unsigned($end - $start);
    $encoded .= encode_unsigned($type_id{$type});
    $previous_end = $end;
}
my $expected_base64 = encode_base64($encoded, q{});

$managed =~ /UpstreamSourceSha256\s*=\s*\n?\s*"([0-9a-f]{64})"/
    or die "managed upstream SHA-256 constant not found\n";
die "managed upstream SHA-256 mismatch\n" if $1 ne $source_sha;
$managed =~ /UpstreamRangeCount\s*=\s*1_376/
    or die "managed upstream range count is missing or changed\n";
$managed =~ /EncodedRanges\s*=\s*\n?\s*"([A-Za-z0-9+\/=]+)"/
    or die "managed EGCB payload not found\n";
my $actual_base64 = $1;
my ($payload_start, $payload_end) = ($-[1], $+[1]);
if ($mode eq '--write' && $actual_base64 ne $expected_base64) {
    substr($managed, $payload_start, $payload_end - $payload_start, $expected_base64);
    write_file($managed_path, $managed);
    $actual_base64 = $expected_base64;
}
if ($actual_base64 ne $expected_base64) {
    my $limit = length($actual_base64) < length($expected_base64)
        ? length($actual_base64)
        : length($expected_base64);
    my $first_difference = 0;
    $first_difference++
        while $first_difference < $limit
        && substr($actual_base64, $first_difference, 1)
            eq substr($expected_base64, $first_difference, 1);
    die "managed EGCB payload differs from deterministic pinned extraction " .
        "at base64 offset $first_difference (actual length=" . length($actual_base64) .
        ", expected length=" . length($expected_base64) . "; actual='" .
        substr($actual_base64, $first_difference, 24) . "', expected='" .
        substr($expected_base64, $first_difference, 24) . "')\n";
}

my $action = $mode eq '--write' ? 'generated' : 'verified';
print "$action unicode=16.0 source_sha256=$source_sha ranges=1376 " .
    "encoded_bytes=" . length($encoded) . " hangul_lv=399 hangul_lvt=399\n";

sub slurp {
    my ($path) = @_;
    open(my $handle, '<', $path) or die "cannot read $path: $!\n";
    binmode($handle);
    local $/;
    return <$handle>;
}

sub write_file {
    my ($path, $contents) = @_;
    open(my $handle, '>', $path) or die "cannot write $path: $!\n";
    binmode($handle);
    print {$handle} $contents or die "cannot write $path: $!\n";
    close($handle) or die "cannot close $path: $!\n";
}

sub encode_unsigned {
    my ($value) = @_;
    my $result = q{};
    do {
        my $byte = $value & 0x7f;
        $value >>= 7;
        $byte |= 0x80 if $value != 0;
        $result .= chr($byte);
    } while ($value != 0);
    return $result;
}
